#!/usr/bin/env python3
"""
Falcon-10B-1.58bit Autonomous Research Daemon (PRIME-Scout Core v2.0)
=====================================================================
Upgraded with:
  1. Anti-Tool-Leakage Filters & Pure Markdown Publication Synthesis
  2. Guaranteed Quantitative Invariant Benchmarking (100% PRIME-Net Execution)
  3. Non-Tautological Mathematical Rigor & Standalone Verification Code
  4. Real-Time Internet Search (GitHub API & CrossRef Scholarly Discovery)
  5. Continuous Thought & Formulation Engine (never goes idle)
  6. Live Telemetry Streamer & SQLite Knowledge Vault
"""

import os
import sys
import time
import json
import sqlite3
import re
import urllib.request
import urllib.parse
import traceback
import psutil

# Ensure scratch Triton directories
scratch_dir = "/home/phil/.gemini/antigravity/scratch/.triton"
os.environ["TRITON_HOME"] = scratch_dir
os.environ["TRITON_CACHE_DIR"] = os.path.join(scratch_dir, "cache")
os.environ["TORCHINDUCTOR_CACHE_DIR"] = os.path.join(scratch_dir, "inductor")
os.environ["TORCH_EXTENSIONS_DIR"] = os.path.join(scratch_dir, "extensions")
os.makedirs(os.environ["TRITON_CACHE_DIR"], exist_ok=True)
os.makedirs(os.environ["TORCHINDUCTOR_CACHE_DIR"], exist_ok=True)
os.makedirs(os.environ["TORCH_EXTENSIONS_DIR"], exist_ok=True)

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, TextStreamer
from prime_moment_attention.primenet_cothinker_bridge import PrimeNetCoThinker

# Paths
BASE_DIR = "/home/phil/.gemini/antigravity/scratch"
REPO_DIR = os.path.join(BASE_DIR, "PRIME-Moment-Attention")
VAULT_DIR = os.path.join(REPO_DIR, "research_vault")
os.makedirs(VAULT_DIR, exist_ok=True)

STATUS_FILE = os.path.join(VAULT_DIR, "live_status.json")
DB_FILE = os.path.join(VAULT_DIR, "research_vault.sqlite3")
DOSSIER_FILE = os.path.join(VAULT_DIR, "THEORY_DOSSIER.md")

SNAPSHOT_PATH = "/home/phil/.cache/huggingface/hub/models--unsloth--DeepSeek-R1-Distill-Qwen-14B-bnb-4bit/snapshots/c73c785bf86971fa5bfd0912ca383a714e925210"
MODEL_ID = SNAPSHOT_PATH if os.path.isdir(SNAPSHOT_PATH) else "unsloth/DeepSeek-R1-Distill-Qwen-14B-bnb-4bit"
DEVICE = "cuda:0" if torch.cuda.is_available() else "cpu"

print(f"[*] Initializing Autonomous Research Daemon (DeepSeek-R1-Distill-14B) on {DEVICE}...")
print(f"[*] Vault Directory: {VAULT_DIR}")

# ---------------------------------------------------------------------------
# Database Setup
# ---------------------------------------------------------------------------
def init_db():
    conn = sqlite3.connect(DB_FILE)
    cur = conn.cursor()
    cur.execute("""
    CREATE TABLE IF NOT EXISTS theories (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        cycle INTEGER,
        timestamp TEXT,
        domain TEXT,
        topic TEXT,
        summary TEXT,
        thought_trace TEXT,
        verified_equations TEXT,
        code_solution TEXT,
        external_sources TEXT
    )
    """)
    cur.execute("""
    CREATE TABLE IF NOT EXISTS literature (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        cycle INTEGER,
        timestamp TEXT,
        source_type TEXT,
        title TEXT,
        url TEXT,
        snippet TEXT
    )
    """)
    cur.execute("""
    CREATE TABLE IF NOT EXISTS socratic_inquiries (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        cycle INTEGER,
        timestamp TEXT,
        question_text TEXT,
        context_snippet TEXT,
        teacher_response TEXT,
        status TEXT DEFAULT 'PENDING',
        student_loss_before REAL,
        student_loss_after REAL
    )
    """)
    conn.commit()
    conn.close()

init_db()

# ---------------------------------------------------------------------------
# Dossier Header Setup
# ---------------------------------------------------------------------------
if not os.path.exists(DOSSIER_FILE):
    with open(DOSSIER_FILE, "w", encoding="utf-8") as f:
        f.write("# Autonomous Theoretical Research Dossier\n")
        f.write("### Generated by Falcon3-10B-Instruct-1.58bit + PRIME-Net Symbolic Co-Thinker\n\n")
        f.write("An ongoing, autonomous scientific discovery record synthesizing Phil (@batteryphil)'s research universe with state-of-the-art open literature and code.\n\n")
        f.write("---\n\n")

# ---------------------------------------------------------------------------
# Telemetry Helper
# ---------------------------------------------------------------------------
class TelemetryManager:
    def __init__(self):
        self.start_time = time.time()
        self.theories_count = 0
        self.repos_studied = 0
        self.papers_ingested = 0
        self.formulas_verified = 0
        self.last_theory_title = "Initializing..."
        self.last_formula = "None"
        
        # Load existing counters from DB if present
        try:
            conn = sqlite3.connect(DB_FILE)
            cur = conn.cursor()
            cur.execute("SELECT COUNT(*) FROM theories")
            self.theories_count = cur.fetchone()[0]
            cur.execute("SELECT COUNT(*) FROM literature")
            self.papers_ingested = cur.fetchone()[0]
            conn.close()
        except Exception:
            pass
        
    def update(self, status: str, domain: str, topic: str, cycle: int, live_thought: str = ""):
        uptime = int(time.time() - self.start_time)
        vram_alloc = torch.cuda.memory_allocated() / (1024**3) if torch.cuda.is_available() else 0.0
        vram_total = torch.cuda.get_device_properties(0).total_memory / (1024**3) if torch.cuda.is_available() else 0.0
        
        vm = psutil.virtual_memory()
        ram_used = (vm.total - vm.available) / (1024**3)
        ram_total = vm.total / (1024**3)
        cpu_pct = psutil.cpu_percent(interval=None)
        
        data = {
            "status": status,
            "cycle": cycle,
            "domain": domain,
            "topic": topic,
            "uptime_seconds": uptime,
            "pid": os.getpid(),
            "vram_allocated_gb": round(vram_alloc, 2),
            "vram_total_gb": round(vram_total, 2),
            "ram_used_gb": round(ram_used, 2),
            "ram_total_gb": round(ram_total, 2),
            "cpu_percent": cpu_pct,
            "live_thought_snippet": live_thought[-600:] if live_thought else "",
            "total_theories_generated": self.theories_count,
            "total_repos_studied": self.repos_studied,
            "total_papers_ingested": self.papers_ingested,
            "total_formulas_verified": self.formulas_verified,
            "last_theory_title": self.last_theory_title,
            "last_verified_formula": self.last_formula,
            "timestamp": time.strftime("%Y-%m-%d %H:%M:%S")
        }
        
        tmp_file = STATUS_FILE + ".tmp"
        with open(tmp_file, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2)
        os.replace(tmp_file, STATUS_FILE)

telemetry = TelemetryManager()
telemetry.update("INITIALIZING_MODEL", "System", "Loading DeepSeek-R1-Distill-Qwen-14B", telemetry.theories_count + 1)

# ---------------------------------------------------------------------------
# Model & PRIME-Net Co-Thinker Initialization
# ---------------------------------------------------------------------------
print(f"[*] Loading Tokenizer & Weights for {MODEL_ID} on {DEVICE}...")
is_local = os.path.isdir(MODEL_ID)
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, trust_remote_code=True, local_files_only=is_local)
model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    torch_dtype=torch.bfloat16,
    device_map=DEVICE,
    trust_remote_code=True,
    local_files_only=is_local
)
model.eval()

cothinker = PrimeNetCoThinker()
vram_boot = torch.cuda.memory_allocated() / (1024**3) if torch.cuda.is_available() else 0.0
print(f"[+] Model loaded successfully! VRAM: {vram_boot:.2f} GB")
telemetry.update("MODEL_READY", "System", "Model loaded in VRAM", telemetry.theories_count + 1)

# ---------------------------------------------------------------------------
# Streaming Callback for Live Monitor Telemetry
# ---------------------------------------------------------------------------
class LiveThoughtStreamer(TextStreamer):
    def __init__(self, tokenizer, on_token_cb, **kwargs):
        super().__init__(tokenizer, **kwargs)
        self.on_token_cb = on_token_cb
        self.accumulated = ""
        self.last_update = 0.0

    def on_finalized_text(self, text: str, stream_end: bool = False):
        self.accumulated += text
        now = time.time()
        if now - self.last_update > 0.8 or stream_end:
            self.last_update = now
            if self.on_token_cb:
                self.on_token_cb(self.accumulated, stream_end)

# ---------------------------------------------------------------------------
# Sanitization Helper (Anti-Tool-Leakage)
# ---------------------------------------------------------------------------
def sanitize_output(text: str) -> str:
    """Eliminates accidental JSON tool-calling schemas and extracts genuine markdown."""
    for token in ['<|assistant|>', '<|user|>', '<|system|>', '<tool_call>', '</tool_call>', '<tool_response>', '</tool_response>']:
        text = text.replace(token, '')

    if '"command":' in text or '"name":' in text:
        # Pattern A: Wrapped in write_to_file
        m = re.search(r'\{\s*"command"\s*:\s*\{.*?"args"\s*:\s*\{.*?"text"\s*:\s*"(.*?)"\s*\}\s*\}\s*\}', text, re.DOTALL)
        if m:
            try:
                extracted = m.group(1).encode("utf-8").decode("unicode_escape", errors="ignore")
                text = extracted
            except Exception:
                pass
        
        # Pattern B: Strip any closed ```json ... ``` blocks containing command/args
        text = re.sub(r'```(?:json)?\s*\{\s*"command".*?\}\s*```', '', text, flags=re.DOTALL)
        # Pattern C: Strip unclosed trailing JSON blocks starting with ```json or {"command":
        text = re.sub(r'```(?:json)?\s*\{\s*"command".*$', '', text, flags=re.DOTALL)
        text = re.sub(r'\{\s*"command"\s*:\s*\{.*?$', '', text, flags=re.DOTALL)
        # Pattern D: Strip standalone closed {"command": ...}
        text = re.sub(r'\{\s*"command"\s*:\s*\{.*?\n\s*\}\s*\}', '', text, flags=re.DOTALL)

    return text.strip()

# ---------------------------------------------------------------------------
# Phil's Repos Ingestion Engine
# ---------------------------------------------------------------------------
PHIL_REPOS = [
    {
        "name": "PRIME-Moment-Attention",
        "path": os.path.join(BASE_DIR, "PRIME-Moment-Attention"),
        "focus": "Constant-state second-order recurrent attention, diagonal Taylor expansions, O(1) memory, multiscale exponential decay banks, invariant latents."
    },
    {
        "name": "PRIME-Net",
        "path": os.path.join(BASE_DIR, "PRIME-Net"),
        "focus": "Automated symbolic regression, Age-Fitness Pareto Optimization (AFPO), reverse Polish notation, discrete invariant discovery from battery & physics telemetry."
    },
    {
        "name": "mamba1and2-to-3",
        "path": os.path.join(BASE_DIR, "mamba1and2-to-3"),
        "focus": "State Space Models (SSMs), selective recurrence, Mamba-1/2 to Mamba-3 SISO architecture conversions and state tracking."
    },
    {
        "name": "prime-revisited",
        "path": os.path.join(BASE_DIR, "prime-revisited"),
        "focus": "Titan MIMO PRIME, 650M-parameter Mamba language model with discrete vote optimizer and autonomous MoE routing."
    },
    {
        "name": "Project-ThreeBody",
        "path": os.path.join(BASE_DIR, "Project-ThreeBody"),
        "focus": "Gravitational three-body problem, numerical integration, periodic orbit hunting (OrbitHunter), Poincaré sections, chaotic invariant manifolds."
    },
    {
        "name": "Project-Ramanujan",
        "path": os.path.join(BASE_DIR, "Project-Ramanujan"),
        "focus": "Polynomial Continued Fractions (PCF), automated Ramanujan machine identity mining for fundamental constants (pi, e, zeta(3), Catalan)."
    },
    {
        "name": "Project-Levitas",
        "path": os.path.join(BASE_DIR, "Project-Levitas"),
        "focus": "Voynich manuscript information theory, homophonic cipher testing, volvelle 2D gear stencils, hidden Markov models, synthetic corpus validation."
    },
    {
        "name": "Project-Kryptos",
        "path": os.path.join(BASE_DIR, "Project-Kryptos"),
        "focus": "Sanborn K4 cipher cryptanalysis, transposition lattices, keyword permutation forward solvers, swarm mining."
    },
    {
        "name": "Project-Beale",
        "path": os.path.join(BASE_DIR, "Project-Beale"),
        "focus": "Statistical cryptanalysis of Beale ciphers, information-theoretic profiling, structural asymmetry between authenticated Cipher 2 and Ciphers 1 & 3."
    },
    {
        "name": "Operating-Organism",
        "path": os.path.join(BASE_DIR, "Operating-Organism"),
        "focus": "Biological & computational organism architectures, decentralized autonomous agency, systems biology models."
    }
]

def sample_repo_context(repo_info: dict) -> str:
    path = repo_info["path"]
    if not os.path.exists(path):
        return "Repo: " + repo_info["name"] + "\nDescription: " + repo_info["focus"]
    return (
        "Repository: " + repo_info["name"] + "\n"
        "Domain Focus: " + repo_info["focus"] + "\n"
        "Key Implemented Baselines: C99 universal binary (`c/bin/prime.com`, 973 KB), "
        "Sub-byte 1-bit bipolar XNOR-popcount GEMM (42.22 GFLOPS, 128 KB matrix footprint), "
        "8-octave fractal power-law memory (tau_k = tau_0 * 2^k, >10^20x signal advantage over distractors), "
        "Non-abelian SU(2) Lie group unitary rotation (10.68M rotations/s, 0.00008768 drift), "
        "and Vectorized Dense/Chunked Parallel Attention (200x training speedup, 88,500+ tok/s)."
    )

# ---------------------------------------------------------------------------
# Internet Search Engine (GitHub & Academic Literature)
# ---------------------------------------------------------------------------
def search_github(query: str, max_results: int = 3) -> list:
    results = []
    try:
        encoded_q = urllib.parse.quote_plus(query)
        url = f"https://api.github.com/search/repositories?q={encoded_q}&sort=stars&order=desc&per_page={max_results}"
        req = urllib.request.Request(url, headers={"User-Agent": "FalconAutonomousResearcher/2.0"})
        with urllib.request.urlopen(req, timeout=8) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            for item in data.get("items", []):
                results.append({
                    "type": "github_repo",
                    "title": item.get("full_name", ""),
                    "url": item.get("html_url", ""),
                    "snippet": item.get("description", "") or "No description",
                    "stars": item.get("stargazers_count", 0)
                })
    except Exception as e:
        print(f"[-] GitHub search error for '{query}': {e}")
    return results

def search_crossref(query: str, max_results: int = 3) -> list:
    results = []
    try:
        encoded_q = urllib.parse.quote_plus(query)
        url = f"https://api.crossref.org/works?query={encoded_q}&rows={max_results}"
        req = urllib.request.Request(url, headers={"User-Agent": "FalconAutonomousResearcher/2.0 (mailto:research@example.com)"})
        with urllib.request.urlopen(req, timeout=8) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            items = data.get("message", {}).get("items", [])
            for item in items:
                titles = item.get("title", [])
                title = titles[0] if titles else "Untitled Paper"
                doi = item.get("DOI", "")
                url = f"https://doi.org/{doi}" if doi else ""
                container = item.get("container-title", ["Academic Journal"])[0] if item.get("container-title") else "Journal"
                results.append({
                    "type": "academic_paper",
                    "title": title,
                    "url": url,
                    "snippet": f"Published in {container}. Subject: {', '.join(item.get('subject', []))[:100]}"
                })
    except Exception as e:
        print(f"[-] CrossRef search error for '{query}': {e}")
    return results

# ---------------------------------------------------------------------------
# Upgraded Research Tracks with Mandatory Exact Equations
# ---------------------------------------------------------------------------
CORE_RESEARCH_TRACKS = [
    {
        "domain": "AI Research: Online Test-Time Training (TTT) vs Offline Empirical Risk Minimization",
        "primary_repo": "PRIME-Moment-Attention",
        "secondary_repo": "PRIME-Net",
        "web_search": "test-time training linear attention continual learning generalization bounds empirical risk minimization",
        "target_formulas": ["4.1483 - 4.0252", "(4.1483 - 4.0252) / 4.1483 * 100.0"],
        "problem_prompt": """
Examine the paradigm shift from traditional offline Empirical Risk Minimization (ERM) on static pre-training corpora to continuous Online Test-Time Training (TTT) with Elastic Synaptic Plasticity.
1. Formulate the statistical learning theory behind why offline pre-training inevitably suffers from out-of-distribution (OOD) generalization collapse, whereas an online TTT model updating plastic weights via gradient descent on the streaming inference manifold achieves vanishing regret.
2. Analyze the trade-offs between static weight freezing (traditional Transformer) versus continuous self-supervised gradient updates (TTT-Linear, TTT-MLP, PRIME continual TTT).
3. Prove why the Elastic Fisher Information regularizer L_elastic = 0.5 * lambda * sum(F_i * (theta_i - theta_0)^2) maintains foundational linguistic reasoning while enabling unbounded factual learning.

MANDATORY NUMERICAL EVALUATION (Section 3):
Calculate the empirical loss reduction observed in our apprentice model (initial 4.1483, adapted 4.0252): [calc: 4.1483 - 4.0252].
Calculate the percentage improvement in reasoning perplexity: [calc: (4.1483 - 4.0252) / 4.1483 * 100.0] %.
Provide a complete, standalone Python/PyTorch verification blueprint comparing offline static inference vs online TTT adaptation on shifting distributions.
"""
    },
    {
        "domain": "Pure Mathematics: Riemannian Information Geometry & Natural Gradients on Statistical Manifolds",
        "primary_repo": "PRIME-Moment-Attention",
        "secondary_repo": "PRIME-Net",
        "web_search": "information geometry Fisher-Rao Riemannian metric natural gradient Amari dual connections",
        "target_formulas": ["1.0 / (1.0 + 4.0**0.5)", "100.0 * (1.0 - 1.0 / 3.0)"],
        "problem_prompt": """
Investigate the differential-geometric structure of probability distributions generated by autoregressive sequence models through Amari's Information Geometry.
1. Derive the Fisher-Rao Riemannian metric tensor g_ij(theta) = E_{x ~ p_theta} [ partial_i log p_theta(x) * partial_j log p_theta(x) ] and prove that it is the unique invariant Riemannian metric under sufficient statistics transformations (Chentsov's Theorem).
2. Contrast standard Euclidean gradient descent with the Natural Gradient descent Delta theta = -eta * G^{-1} grad L on the statistical manifold, proving why Euclidean updates cause catastrophic interference across curved parameter basins.
3. Derive the dynamic learning rate scaling factor eta_eff = eta_0 / (1 + sqrt(F_i)) as a diagonal Riemannian geodesic projection that bounds displacement along high-curvature sectional manifolds.

MANDATORY NUMERICAL EVALUATION (Section 3):
Calculate the effective learning rate damping factor for Fisher curvature F=4.0: [calc: 1.0 / (1.0 + 4.0**0.5)].
Calculate the percentage curvature stiffening over Euclidean space: [calc: 100.0 * (1.0 - 1.0 / 3.0)] %.
Provide a complete mathematical derivation and a runnable SymPy verification script.
"""
    },
    {
        "domain": "AI Research: State Space Duality (SSD), Mamba-2 & 1-Semiseparable Structured Matrices",
        "primary_repo": "PRIME-Moment-Attention",
        "secondary_repo": "PRIME-Net",
        "web_search": "State Space Duality Mamba-2 structured matrices 1-semiseparable chunked associative scan",
        "target_formulas": ["2048 * 64 * 4 / 1024", "4641.44 / 23.12"],
        "problem_prompt": """
Synthesize the foundational breakthrough of State Space Duality (SSD) introduced by Dao and Gu (2024), unifying continuous-time State Space Models (SSMs) and Linear Attention via structured 1-semiseparable matrices.
1. Prove the exact mathematical equivalence between the discrete SSM recurrence h_t = A_t h_{t-1} + B_t x_t and the masked matrix multiplication Y = (M * (Q K^T)) V, where M is a semiseparable decay matrix.
2. Derive the 3D Batch GEMM formulation for chunked inter-state propagation Delta S_c = sum_{j=0}^{C-1} lambda^{C-1-j} k_j v_j^T, proving that critical path depth drops from O(L) to O(L/C + log(L/C)).
3. Contrast 1st-order linear attention with PRIME's 2nd-order Taylor moment attention in terms of state manifold rank capacity and representation expressivity.

MANDATORY NUMERICAL EVALUATION (Section 3):
Calculate the intermediate chunk state memory in KB for chunk size C=64, D=64, float32 (2048 * 64 * 4 bytes): [calc: 2048 * 64 * 4 / 1024] KB.
Calculate our measured AMD ROCm 7.2 parallel SSD speedup ratio (4641.44 ms down to 23.12 ms): [calc: 4641.44 / 23.12]x.
Provide a complete, standalone Python implementation blueprint for 1-semiseparable chunked associative scan.
"""
    },
    {
        "domain": "Applied Mathematics: Symplectic Manifolds & Hamiltonian Flow Conservation in Recurrent Latents",
        "primary_repo": "PRIME-Moment-Attention",
        "secondary_repo": "PRIME-Net",
        "web_search": "symplectic integrator Hamiltonian mechanics neural ODE Liouville theorem energy conservation",
        "target_formulas": ["3.567271 - 3.350956", "(3.567271 - 3.350956) / 3.567271 * 100.0"],
        "problem_prompt": """
Formulate recurrent sequence models as continuous-time Hamiltonian dynamical systems on a 2D-dimensional symplectic phase-space manifold M with canonical coordinates (q_t, p_t).
1. Define the Hamiltonian H(q, p) governing latent state evolution, and prove that the symplectic 2-form omega = sum_{i=1}^D dq_i ^ dp_i is strictly preserved along trajectory flows (Liouville's Theorem).
2. Prove that standard RNNs and Transformers violate symplectic structure, causing latent phase-space volume collapse or divergence over long contexts, whereas a symplectic Cayley integrator R(theta) = (I - J*theta/2)^(-1) (I + J*theta/2) guarantees unconditional norm and energy preservation.
3. Formulate the exact Poisson bracket {F, H} for non-dissipative memory retention across multi-million token sequences.

MANDATORY NUMERICAL EVALUATION (Section 3):
Compute the exact phase-space drift across 10,000 Cayley steps (initial 3.567271, final 3.350956): [calc: 3.567271 - 3.350956].
Compute the percentage stability ratio: [calc: (3.567271 - 3.350956) / 3.567271 * 100.0] %.
Provide a complete, runnable C99 symplectic integrator implementation.
"""
    },
    {
        "domain": "AI Research: DeepSeek-R1 Cognitive Mechanics: Reasoning-Time Compute & Latent Policy Search",
        "primary_repo": "PRIME-Moment-Attention",
        "secondary_repo": "prime-revisited",
        "web_search": "DeepSeek-R1 reasoning compute scaling test-time search chain of thought process reward model",
        "target_formulas": ["1000 * 450", "32 / 32 * 5.0"],
        "problem_prompt": """
Deconstruct the cognitive mechanics and scaling laws of reasoning-time compute popularized by DeepSeek-R1 and OpenAI o1/o3.
1. Formulate the mathematical relationship between the number of reasoning tokens in <think>...</think> and task accuracy: P(correct) propto log(N_thinking), proving that extended chain-of-thought acts as an implicit Monte Carlo Tree Search (MCTS) over the token policy distribution.
2. Analyze the entropy dynamics during reasoning: demonstrate how entropy spikes indicate branch exploration and backtracking, while sharp entropy drops signal conceptual consolidation and proof convergence.
3. Design a Process Reward Model (PRM) formulation that evaluates intermediate token derivations step-by-step to prune hallucinatory reasoning trajectories in the apprentice model.

MANDATORY NUMERICAL EVALUATION (Section 3):
Calculate the maximum cognitive compute budget in token operations for a 1000-prompt batch with 450 thought tokens each: [calc: 1000 * 450].
Compute the branching depth factor for 32 explored reasoning branches: [calc: 32 / 32 * 5.0].
Provide a complete Python implementation blueprint simulating entropy-guided self-correction during sequence generation.
"""
    },
    {
        "domain": "Pure Mathematics: Optimal Transport & Entropic Wasserstein Barycenters in Latent Spaces",
        "primary_repo": "PRIME-Moment-Attention",
        "secondary_repo": "PRIME-Net",
        "web_search": "optimal transport Wasserstein distance Sinkhorn algorithm entropic regularization cross-attention",
        "target_formulas": ["1.0 / 0.05", "256 * 256 * 4 / 1024"],
        "problem_prompt": """
Analyze the geometry of neural feature representations through the lens of Monge-Kantorovich Optimal Transport theory.
1. Formulate the 2-Wasserstein distance W_2(mu, nu) = (inf_{gamma in Pi} int ||x - y||^2 d gamma(x, y))^{1/2} between token probability distributions across consecutive model layers.
2. Prove that standard dot-product Softmax attention is equivalent to an unregularized assignment problem, whereas Sinkhorn-regularized optimal transport achieves smooth, robust concept alignment without quadratic token blowup.
3. Derive the Wasserstein barycenter algorithm for fusing multi-modal token distributions into a unified latent manifold.

MANDATORY NUMERICAL EVALUATION (Section 3):
Calculate the Sinkhorn scaling penalty for regularization parameter gamma=0.05: [calc: 1.0 / 0.05].
Calculate the cost matrix memory in KB for a 256x256 token matching problem (256 * 256 * 4 bytes): [calc: 256 * 256 * 4 / 1024] KB.
Provide a complete, runnable PyTorch Sinkhorn optimal transport implementation.
"""
    },
    {
        "domain": "AI Research: Dynamic Sparse Mixture-of-Experts (MoE) & Progressive Parameter Allocation",
        "primary_repo": "PRIME-Moment-Attention",
        "secondary_repo": "PRIME-Net",
        "web_search": "dynamic mixture of experts sparse routing capacity factor load balancing expert specialization",
        "target_formulas": ["125 * 1.5", "187.5 - 125.0"],
        "problem_prompt": """
Investigate dynamic network architecture expansion and progressive parameter allocation for lifelong AI learners.
1. Formulate the mathematics of Sparse Mixture-of-Experts (MoE) routing: y = sum_{i in TopK} G(x)_i E_i(x), where G(x) = Softmax(KeepTopK(H(x), k)).
2. Analyze the routing collapse phenomenon and prove why the auxiliary load balancing loss L_aux = alpha * N * sum_{i=1}^N f_i P_i ensures uniform expert utilization.
3. Derive the Net2Net zero-residual width expansion theorem: prove that appending zero-initialized columns to output projections enables instant parameter expansion (e.g. 125M -> 187.5M) with 0.000000 logit drift at step zero, providing fresh plastic capacity with zero Fisher curvature.

MANDATORY NUMERICAL EVALUATION (Section 3):
Calculate the expanded parameter count in millions for a 1.5x width expansion on our 125M model: [calc: 125 * 1.5] M.
Calculate the net parameter headroom added to the plastic memory pool: [calc: 187.5 - 125.0] M.
Provide a complete, standalone Python implementation blueprint for on-the-fly Net2Net expansion.
"""
    },
    {
        "domain": "Pure Mathematics: Sheaf Theory & Čech Cohomology for Context Consistency in LLMs",
        "primary_repo": "PRIME-Moment-Attention",
        "secondary_repo": "PRIME-Net",
        "web_search": "sheaf theory Čech cohomology global sections consistency topological data analysis LLM",
        "target_formulas": ["768 * 12 * 4 / 1024", "1024 * 768 * 4 / (1024**2)"],
        "problem_prompt": """
Formulate context consistency and hallucination prevention in large language models using the mathematical framework of Sheaf Theory and Homological Algebra.
1. Model the input prompt and conversation history as an open cover U = {U_i} of a topological context space X, where each U_i represents a local context window or reasoning step.
2. Define the sheaf of sections F assigning local factual representations to each open set U_i with restriction maps rho_{ij}: F(U_i) -> F(U_i cap U_j).
3. Prove that factual hallucinations correspond precisely to non-trivial elements in the first Čech Cohomology group H^1(U, F) = Ker(delta_1) / Im(delta_0), where the failure of local reasoning patches to glue into a global section reveals contradictory deductions.

MANDATORY NUMERICAL EVALUATION (Section 3):
Calculate the restriction map footprint in KB for D=768 across 12 layers: [calc: 768 * 12 * 4 / 1024] KB.
Calculate the activation sheaf memory in MB for context L=1024, D=768 in float32: [calc: 1024 * 768 * 4 / (1024**2)] MB.
Provide a complete mathematical derivation and runnable SymPy verification script.
"""
    },
    {
        "domain": "Applied Mathematics: Non-Hermitian Pseudospectra & Transient Dynamics in Recurrent Networks",
        "primary_repo": "PRIME-Moment-Attention",
        "secondary_repo": "PRIME-Net",
        "web_search": "non-hermitian matrix pseudospectra transient growth recurrent neural network stability Trefethen",
        "target_formulas": ["1.0 / (1.0 - 0.995)", "0.995**1000"],
        "problem_prompt": """
Investigate the numerical stability of deep recurrent neural state transitions through Non-Hermitian Operator Theory and Trefethen's Pseudospectra.
1. Prove why standard eigenvalue analysis fails for non-normal transition matrices W (where W W^T != W^T W), allowing transient amplification ||W^t|| >> (rho(W))^t to trigger explosive gradient blowups even when the spectral radius rho(W) < 1.
2. Define the epsilon-pseudospectrum Lambda_epsilon(W) = {z in C : ||(zI - W)^(-1)|| > 1/epsilon}, and derive the Kreiss Matrix Theorem lower and upper bounds on transient amplification.
3. Formulate the Schur-form unitary factorization W = Q T Q^dagger to isolate non-normal cross-coupling terms and guarantee stable memory propagation across million-token contexts.

MANDATORY NUMERICAL EVALUATION (Section 3):
Calculate the resolvent norm upper bound for continuous decay lambda=0.995: [calc: 1.0 / (1.0 - 0.995)].
Calculate the steady-state attenuation after 1000 recurrent steps: [calc: 0.995**1000].
Provide a complete Python implementation blueprint computing and visualizing the epsilon-pseudospectrum of recurrent matrices.
"""
    },
    {
        "domain": "AI Research: Thermodynamic Information Limits & Landauer Horizons in Neural Memory",
        "primary_repo": "PRIME-Moment-Attention",
        "secondary_repo": "PRIME-Net",
        "web_search": "Landauer principle thermodynamic cost of information neural network memory capacity channel capacity",
        "target_formulas": ["2.0**(-24)", "-16.635532 / (-0.0050125)"],
        "problem_prompt": """
Examine the physical and information-theoretic limits of neural memory retention through the lens of Landauer's Principle and Shannon Channel Capacity.
1. By Landauer's Principle, the erasure of one bit of information dissipates a minimum thermodynamic heat of Delta Q = k_B * T * ln(2). Prove that unitary and recurrent linear attention state updates S_t = lambda * S_{t-1} + k_t v_t^T are information-preserving transformations, avoiding thermodynamic erasure until signals drop below machine precision.
2. Calculate the Numerical Landauer Horizon tau_crit = ln(epsilon_machine) / ln(lambda), the exact step count where exponential attenuation drops below IEEE-754 float32 single-precision machine epsilon (2^-24).
3. Prove that expanding from 1st-order vector states to 2nd-order Taylor moment matrices S_2 in R^{D x D} expands orthogonal subspace capacity by a factor of D, delaying semantic collision exponentially.

MANDATORY NUMERICAL EVALUATION (Section 3):
Compute IEEE-754 float32 single-precision machine epsilon (2^-24): [calc: 2.0**(-24)].
Compute the exact token horizon tau_crit for decay lambda=0.995 before signal hits float32 epsilon: [calc: -16.635532 / (-0.0050125)].
Provide a complete, runnable Python/C99 verification script for adjoint memory deconvolution.
"""
    }
]

# ---------------------------------------------------------------------------
# Socratic Inquiry & Clarification Engine
# ---------------------------------------------------------------------------
def answer_pending_socratic_inquiries(model, tokenizer, cothinker):
    """
    Checks for pending mathematical inquiries from the Student Model (PRIME-125M).
    Generates step-by-step cognitive derivations with <think> traces using DeepSeek-R1,
    verifies arithmetic symbolically with PRIME-Net, and writes clarifications to the vault.
    """
    try:
        conn = sqlite3.connect(DB_FILE)
        cur = conn.cursor()
        cur.execute("""
            SELECT id, cycle, question_text, context_snippet 
            FROM socratic_inquiries 
            WHERE status = 'PENDING' 
            ORDER BY id ASC LIMIT 1
        """)
        row = cur.fetchone()
        if not row:
            conn.close()
            return
            
        inquiry_id, inq_cycle, question_text, context_snippet = row
        print(f"\n[?] >>> TEACHER SOCRATIC MENTORSHIP: Addressing Student Inquiry #{inquiry_id} (Cycle {inq_cycle}) <<<")
        print(f"    Question: {question_text}")
        print(f"    Context:  {context_snippet[:120]}...")
        
        system_prompt = (
            "You are the Lead Theoretical Architect and Teacher (DeepSeek-R1-Distill-14B). "
            "Your apprentice model (PRIME-125M) is studying your theoretical papers and needs guidance. "
            "First, engage in your step-by-step cognitive reasoning inside <think>...</think>, analyzing the exact mathematical derivation and intuitive physics. "
            "Then, provide the complete, crystal-clear derivation with explicit intermediate steps so the student can absorb the exact reasoning trajectory."
        )
        user_prompt = (
            f"Regarding Research Paper Cycle {inq_cycle}:\n"
            f"Context Snippet:\n\"{context_snippet}\"\n\n"
            f"Student Question:\n\"{question_text}\"\n\n"
            "Please provide a rigorous mathematical derivation and clear physical intuition to clarify this concept."
        )
        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ]
        if hasattr(tokenizer, "apply_chat_template") and tokenizer.chat_template:
            prompt_text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
        else:
            prompt_text = f"System: {system_prompt}\nUser: {user_prompt}\nAssistant: <think>\n"
            
        inputs = tokenizer(prompt_text, return_tensors="pt", max_length=1280, truncation=True).to(DEVICE)
        with torch.no_grad():
            out = model.generate(
                **inputs,
                max_new_tokens=450,
                temperature=0.6,
                top_p=0.95,
                do_sample=True
            )
        raw_ans = tokenizer.decode(out[0][inputs.input_ids.shape[1]:], skip_special_tokens=True).strip()
        del inputs, out
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
            
        clean_ans = sanitize_output(raw_ans)
        verified_ans, _ = cothinker.intercept_and_solve(clean_ans)
        
        cur.execute("""
            UPDATE socratic_inquiries 
            SET teacher_response = ?, status = 'ANSWERED' 
            WHERE id = ?
        """, (verified_ans, inquiry_id))
        conn.commit()
        conn.close()
        print(f"[+] Socratic Clarification generated ({len(verified_ans)} chars) and recorded in SQLite!")
        
        with open(DOSSIER_FILE, "a", encoding="utf-8") as f:
            f.write(f"\n### Socratic Clarification for Student (Inquiry #{inquiry_id} on Cycle {inq_cycle})\n\n")
            f.write(f"**Student Inquiry**: *{question_text}*\n\n")
            f.write(f"**Teacher Response & Derivation**:\n\n{verified_ans}\n\n---\n\n")
    except Exception as e:
        print(f"[-] Error answering socratic inquiry: {e}")

# ---------------------------------------------------------------------------
# Main Autonomous Loop v2.0
# ---------------------------------------------------------------------------
def run_autonomous_research_loop():
    track_idx = telemetry.theories_count
    cycle = telemetry.theories_count + 1
    
    print("\n" + "=" * 80)
    print("      FALCON3-10B-1.58BIT AUTONOMOUS RESEARCH DAEMON v2.0 (UPGRADED)")
    print("=" * 80 + "\n")
    
    while True:
        try:
            track = CORE_RESEARCH_TRACKS[track_idx % len(CORE_RESEARCH_TRACKS)]
            domain = track["domain"]
            primary_repo_name = track["primary_repo"]
            secondary_repo_name = track["secondary_repo"]
            web_query = track["web_search"]
            problem_prompt = track["problem_prompt"].strip()
            
            topic_title = f"{domain}: Cycle {cycle}"
            telemetry.update("STUDYING_REPOS", domain, topic_title, cycle)
            print(f"\n[{time.strftime('%X')}] === STARTING RESEARCH CYCLE {cycle} ===")
            print(f"[*] Target Domain: {domain}")
            print(f"[*] Target Repos: {primary_repo_name} & {secondary_repo_name}")
            
            primary_repo = next((r for r in PHIL_REPOS if r["name"] == primary_repo_name), None)
            secondary_repo = next((r for r in PHIL_REPOS if r["name"] == secondary_repo_name), None)
            
            repo_context = ""
            if primary_repo:
                repo_context += sample_repo_context(primary_repo) + "\n\n"
            if secondary_repo:
                repo_context += sample_repo_context(secondary_repo)
            telemetry.repos_studied += 2
            
            telemetry.update("SEARCHING_WEB", domain, topic_title, cycle)
            print(f"[*] Querying Internet for: '{web_query}'...")
            gh_results = search_github(web_query, max_results=2)
            crossref_results = search_crossref(web_query, max_results=2)
            all_literature = gh_results + crossref_results
            telemetry.papers_ingested += len(all_literature)
            
            lit_summary = ""
            for item in all_literature:
                lit_summary += f"- [{item['type'].upper()}] {item['title']} ({item.get('url', '')}): {item['snippet']}\n"
                try:
                    conn = sqlite3.connect(DB_FILE)
                    cur = conn.cursor()
                    cur.execute("""
                    INSERT INTO literature (cycle, timestamp, source_type, title, url, snippet)
                    VALUES (?, ?, ?, ?, ?, ?)
                    """, (cycle, time.strftime("%Y-%m-%d %H:%M:%S"), item["type"], item["title"], item.get("url", ""), item["snippet"]))
                    conn.commit()
                    conn.close()
                except Exception:
                    pass
                    
            print(f"[+] Retrieved {len(all_literature)} relevant external resources.")
            
            # Step 3: Upgraded Deep Formulation
            telemetry.update("THINKING", domain, topic_title, cycle)
            print(f"[*] Prompting Falcon3-10B-1.58bit with anti-leakage constraints & mandatory quantitative tags...")
            
            system_prompt = (
                "You are an elite theoretical physicist, sequence model architect, and applied mathematician. "
                "You are writing formal research papers in Phil's laboratory.\n\n"
                "CRITICAL FORMAT RULES (STRICT):\n"
                "1. NEVER emit JSON commands, tool calls, or schemas (e.g. NEVER write '{\"command\": ...}', 'write_to_file', or 'browse_website'). Write directly in standard technical Markdown.\n"
                "2. Reason through the problem inside <think>...</think>.\n"
                "3. Structure each paper into these 4 sections:\n"
                "   # Theoretical Formulation & Core Thesis\n"
                "   ## Mathematical Derivations & State Transitions\n"
                "   ## Quantitative Numerical Benchmarks: Compute every requested value inside [calc: <formula>] or <<formula>> tags so PRIME-Net can symbolically verify it (e.g. [calc: 32 * 512 * 4]).\n"
                "   ## Implementation & Verification Blueprint (Python / C99)\n"
                "4. Provide non-circular, mathematically rigorous theorems with precise bounds.\n"
                "5. Provide a complete, runnable Python or C99 verification implementation in markdown codeblocks."
            )
            
            user_prompt = f"""
=== FRONTIER RESEARCH CHALLENGE ===
Domain: {domain}
Primary Repository: {primary_repo_name}
Secondary Repository: {secondary_repo_name}

{problem_prompt}

=== EXTERNAL LITERATURE & CODE DISCOVERED ===
{lit_summary}

=== LOCAL REPOSITORY CONTEXT ===
{repo_context}
"""
            messages = [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ]
            
            if hasattr(tokenizer, "apply_chat_template") and tokenizer.chat_template:
                prompt_text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
            else:
                prompt_text = f"System: {system_prompt}\nUser: {user_prompt}\nAssistant: <think>\n"
                
            inputs = tokenizer(prompt_text, return_tensors="pt", max_length=1280, truncation=True).to(DEVICE)
            
            telemetry.update("THINKING", domain, topic_title, cycle, live_thought="Synthesizing rigorous mathematical derivation and C99 blueprints...")
            print(f"[*] Generating theoretical formulation with DeepSeek-R1-Distill-14B (prompt: {inputs.input_ids.shape[1]} tokens, max 1000 tokens)...")
            gen_start = time.time()
            with torch.no_grad():
                out = model.generate(
                    **inputs,
                    max_new_tokens=1000,
                    temperature=0.6,
                    top_p=0.95,
                    do_sample=True
                )
            gen_duration = time.time() - gen_start
            raw_response = tokenizer.decode(out[0][inputs.input_ids.shape[1]:], skip_special_tokens=True).strip()
            print(f"[+] Generation finished in {gen_duration:.2f}s ({len(raw_response)} chars).")
            del inputs, out
            if torch.cuda.is_available():
                torch.cuda.empty_cache()
            
            # Sanitize output (removes any accidental JSON schema leakage)
            clean_response = sanitize_output(raw_response)
            
            # Step 4: PRIME-Net Symbolic Verification
            telemetry.update("VERIFYING", domain, topic_title, cycle, live_thought=clean_response)
            verified_response, injections = cothinker.intercept_and_solve(clean_response, target_formulas=track.get("target_formulas"))
            
            telemetry.formulas_verified += len(injections)
            if injections:
                telemetry.last_formula = f"{injections[0]['expr']} = {injections[0]['result']}"
                print(f"[+] PRIME-Net verified {len(injections)} formulas symbolically in microseconds!")
                for inj in injections:
                    print(f"    - {inj['expr']} = {inj['result']}")
            else:
                print(f"[-] Note: 0 formulas caught by <<...>> pattern.")
                
            # Extract summary & thought
            thought_match = re.search(r"<think>(.*?)</think>", clean_response, re.DOTALL)
            thought_trace = thought_match.group(1).strip() if thought_match else clean_response[:400]
            summary_text = re.sub(r"<think>.*?</think>", "", verified_response, flags=re.DOTALL).strip()
            if not summary_text:
                summary_text = verified_response[:600]
                
            # Step 5: Save Theory to Knowledge Vault
            telemetry.theories_count += 1
            telemetry.last_theory_title = f"Cycle {cycle}: {domain}"
            telemetry.update("SAVING", domain, topic_title, cycle, live_thought=clean_response)
            
            # Record in SQLite
            try:
                conn = sqlite3.connect(DB_FILE)
                cur = conn.cursor()
                cur.execute("""
                INSERT INTO theories (cycle, timestamp, domain, topic, summary, thought_trace, verified_equations, code_solution, external_sources)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
                """, (
                    cycle,
                    time.strftime("%Y-%m-%d %H:%M:%S"),
                    domain,
                    topic_title,
                    summary_text[:1500],
                    thought_trace[:4000],
                    json.dumps(injections),
                    summary_text,
                    json.dumps([item["title"] for item in all_literature])
                ))
                conn.commit()
                conn.close()
            except Exception as e:
                print(f"[-] SQLite insertion error: {e}")
                
            # Record in Markdown Dossier
            with open(DOSSIER_FILE, "a", encoding="utf-8") as f:
                f.write(f"## Cycle {cycle}: {domain}\n\n")
                f.write(f"**Timestamp**: {time.strftime('%Y-%m-%d %H:%M:%S')}  \n")
                f.write(f"**Synthesized Repos**: `{primary_repo_name}` & `{secondary_repo_name}`  \n")
                f.write(f"**External Literature Found**: {len(all_literature)} sources  \n")
                if injections:
                    f.write(f"**PRIME-Net Verifications**: {len(injections)} formulas verified symbolically  \n")
                    for inj in injections:
                        f.write(f"  - `{inj['expr']}` = **`{inj['result']}`**\n")
                f.write("\n### Deep Cognitive Thought Trace\n")
                f.write(f"```text\n{thought_trace[:2500]}\n```\n\n")
                f.write("### Formulated Theory & Solution Blueprint\n\n")
                f.write(f"{summary_text}\n\n")
                f.write("---\n\n")
                
            print(f"[+] Cycle {cycle} complete! Theory saved to {DOSSIER_FILE}")
            
            # Step 5b: Socratic Mentorship of Student Model (PRIME-125M)
            answer_pending_socratic_inquiries(model, tokenizer, cothinker)
            
            # Step 6: Advance & Cleanup
            cycle += 1
            track_idx += 1
            
            if torch.cuda.is_available():
                torch.cuda.empty_cache()
                
            time.sleep(5)
            
        except Exception as e:
            print(f"[!] Exception in research cycle: {e}")
            traceback.print_exc()
            if torch.cuda.is_available():
                torch.cuda.empty_cache()
            time.sleep(10)
            track_idx += 1

if __name__ == "__main__":
    run_autonomous_research_loop()
