#!/usr/bin/env python3
"""
Falcon-10B-1.58bit Autonomous Research Daemon (PRIME-Scout Core v2.0)
=====================================================================
Upgraded with:
  1. Anti-Tool-Leakage Filters & Pure Markdown Publication Synthesis
  2. Guaranteed Quantitative Invariant Benchmarking (100% PRIME-Net Execution)
  3. Non-Tautological Mathematical Rigor & Standalone Verification Code
  4. Real-Time Internet Search (GitHub API & CrossRef Scholarly Discovery)
  5. Continuous Thought & Formulation Engine (never goes idle)
  6. Live Telemetry Streamer & SQLite Knowledge Vault
"""

import os
import sys
import time
import json
import sqlite3
import re
import urllib.request
import urllib.parse
import traceback
import psutil

# Ensure scratch Triton directories
scratch_dir = "/home/phil/.gemini/antigravity/scratch/.triton"
os.environ["TRITON_HOME"] = scratch_dir
os.environ["TRITON_CACHE_DIR"] = os.path.join(scratch_dir, "cache")
os.environ["TORCHINDUCTOR_CACHE_DIR"] = os.path.join(scratch_dir, "inductor")
os.environ["TORCH_EXTENSIONS_DIR"] = os.path.join(scratch_dir, "extensions")
os.makedirs(os.environ["TRITON_CACHE_DIR"], exist_ok=True)
os.makedirs(os.environ["TORCHINDUCTOR_CACHE_DIR"], exist_ok=True)
os.makedirs(os.environ["TORCH_EXTENSIONS_DIR"], exist_ok=True)

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, TextStreamer
from prime_moment_attention.primenet_cothinker_bridge import PrimeNetCoThinker

# Paths
BASE_DIR = "/home/phil/.gemini/antigravity/scratch"
REPO_DIR = os.path.join(BASE_DIR, "PRIME-Moment-Attention")
VAULT_DIR = os.path.join(REPO_DIR, "research_vault")
os.makedirs(VAULT_DIR, exist_ok=True)

STATUS_FILE = os.path.join(VAULT_DIR, "live_status.json")
DB_FILE = os.path.join(VAULT_DIR, "research_vault.sqlite3")
DOSSIER_FILE = os.path.join(VAULT_DIR, "THEORY_DOSSIER.md")

SNAPSHOT_PATH = "/home/phil/.cache/huggingface/hub/models--unsloth--DeepSeek-R1-Distill-Qwen-14B-bnb-4bit/snapshots/c73c785bf86971fa5bfd0912ca383a714e925210"
MODEL_ID = SNAPSHOT_PATH if os.path.isdir(SNAPSHOT_PATH) else "unsloth/DeepSeek-R1-Distill-Qwen-14B-bnb-4bit"
DEVICE = "cuda:0" if torch.cuda.is_available() else "cpu"

print(f"[*] Initializing Autonomous Research Daemon (DeepSeek-R1-Distill-14B) on {DEVICE}...")
print(f"[*] Vault Directory: {VAULT_DIR}")

# ---------------------------------------------------------------------------
# Database Setup
# ---------------------------------------------------------------------------
def init_db():
    conn = sqlite3.connect(DB_FILE)
    cur = conn.cursor()
    cur.execute("""
    CREATE TABLE IF NOT EXISTS theories (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        cycle INTEGER,
        timestamp TEXT,
        domain TEXT,
        topic TEXT,
        summary TEXT,
        thought_trace TEXT,
        verified_equations TEXT,
        code_solution TEXT,
        external_sources TEXT
    )
    """)
    cur.execute("""
    CREATE TABLE IF NOT EXISTS literature (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        cycle INTEGER,
        timestamp TEXT,
        source_type TEXT,
        title TEXT,
        url TEXT,
        snippet TEXT
    )
    """)
    cur.execute("""
    CREATE TABLE IF NOT EXISTS socratic_inquiries (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        cycle INTEGER,
        timestamp TEXT,
        question_text TEXT,
        context_snippet TEXT,
        teacher_response TEXT,
        status TEXT DEFAULT 'PENDING',
        student_loss_before REAL,
        student_loss_after REAL
    )
    """)
    conn.commit()
    conn.close()

init_db()

# ---------------------------------------------------------------------------
# Dossier Header Setup
# ---------------------------------------------------------------------------
if not os.path.exists(DOSSIER_FILE):
    with open(DOSSIER_FILE, "w", encoding="utf-8") as f:
        f.write("# Autonomous Theoretical Research Dossier\n")
        f.write("### Generated by Falcon3-10B-Instruct-1.58bit + PRIME-Net Symbolic Co-Thinker\n\n")
        f.write("An ongoing, autonomous scientific discovery record synthesizing Phil (@batteryphil)'s research universe with state-of-the-art open literature and code.\n\n")
        f.write("---\n\n")

# ---------------------------------------------------------------------------
# Telemetry Helper
# ---------------------------------------------------------------------------
class TelemetryManager:
    def __init__(self):
        self.start_time = time.time()
        self.theories_count = 0
        self.repos_studied = 0
        self.papers_ingested = 0
        self.formulas_verified = 0
        self.last_theory_title = "Initializing..."
        self.last_formula = "None"
        
        # Load existing counters from DB if present
        try:
            conn = sqlite3.connect(DB_FILE)
            cur = conn.cursor()
            cur.execute("SELECT COUNT(*) FROM theories")
            self.theories_count = cur.fetchone()[0]
            cur.execute("SELECT COUNT(*) FROM literature")
            self.papers_ingested = cur.fetchone()[0]
            conn.close()
        except Exception:
            pass
        
    def update(self, status: str, domain: str, topic: str, cycle: int, live_thought: str = ""):
        uptime = int(time.time() - self.start_time)
        vram_alloc = torch.cuda.memory_allocated() / (1024**3) if torch.cuda.is_available() else 0.0
        vram_total = torch.cuda.get_device_properties(0).total_memory / (1024**3) if torch.cuda.is_available() else 0.0
        
        vm = psutil.virtual_memory()
        ram_used = (vm.total - vm.available) / (1024**3)
        ram_total = vm.total / (1024**3)
        cpu_pct = psutil.cpu_percent(interval=None)
        
        data = {
            "status": status,
            "cycle": cycle,
            "domain": domain,
            "topic": topic,
            "uptime_seconds": uptime,
            "pid": os.getpid(),
            "vram_allocated_gb": round(vram_alloc, 2),
            "vram_total_gb": round(vram_total, 2),
            "ram_used_gb": round(ram_used, 2),
            "ram_total_gb": round(ram_total, 2),
            "cpu_percent": cpu_pct,
            "live_thought_snippet": live_thought[-600:] if live_thought else "",
            "total_theories_generated": self.theories_count,
            "total_repos_studied": self.repos_studied,
            "total_papers_ingested": self.papers_ingested,
            "total_formulas_verified": self.formulas_verified,
            "last_theory_title": self.last_theory_title,
            "last_verified_formula": self.last_formula,
            "timestamp": time.strftime("%Y-%m-%d %H:%M:%S")
        }
        
        tmp_file = STATUS_FILE + ".tmp"
        with open(tmp_file, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2)
        os.replace(tmp_file, STATUS_FILE)

telemetry = TelemetryManager()
telemetry.update("INITIALIZING_MODEL", "System", "Loading DeepSeek-R1-Distill-Qwen-14B", telemetry.theories_count + 1)

# ---------------------------------------------------------------------------
# Model & PRIME-Net Co-Thinker Initialization
# ---------------------------------------------------------------------------
print(f"[*] Loading Tokenizer & Weights for {MODEL_ID} on {DEVICE}...")
is_local = os.path.isdir(MODEL_ID)
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, trust_remote_code=True, local_files_only=is_local)
model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    torch_dtype=torch.bfloat16,
    device_map=DEVICE,
    trust_remote_code=True,
    local_files_only=is_local
)
model.eval()

cothinker = PrimeNetCoThinker()
vram_boot = torch.cuda.memory_allocated() / (1024**3) if torch.cuda.is_available() else 0.0
print(f"[+] Model loaded successfully! VRAM: {vram_boot:.2f} GB")
telemetry.update("MODEL_READY", "System", "Model loaded in VRAM", telemetry.theories_count + 1)

# ---------------------------------------------------------------------------
# Streaming Callback for Live Monitor Telemetry
# ---------------------------------------------------------------------------
class LiveThoughtStreamer(TextStreamer):
    def __init__(self, tokenizer, on_token_cb, **kwargs):
        super().__init__(tokenizer, **kwargs)
        self.on_token_cb = on_token_cb
        self.accumulated = ""
        self.last_update = 0.0

    def on_finalized_text(self, text: str, stream_end: bool = False):
        self.accumulated += text
        now = time.time()
        if now - self.last_update > 0.8 or stream_end:
            self.last_update = now
            if self.on_token_cb:
                self.on_token_cb(self.accumulated, stream_end)

# ---------------------------------------------------------------------------
# Sanitization Helper (Anti-Tool-Leakage)
# ---------------------------------------------------------------------------
def sanitize_output(text: str) -> str:
    """Eliminates accidental JSON tool-calling schemas and extracts genuine markdown."""
    for token in ['<|assistant|>', '<|user|>', '<|system|>', '<tool_call>', '</tool_call>', '<tool_response>', '</tool_response>']:
        text = text.replace(token, '')

    if '"command":' in text or '"name":' in text:
        # Pattern A: Wrapped in write_to_file
        m = re.search(r'\{\s*"command"\s*:\s*\{.*?"args"\s*:\s*\{.*?"text"\s*:\s*"(.*?)"\s*\}\s*\}\s*\}', text, re.DOTALL)
        if m:
            try:
                extracted = m.group(1).encode("utf-8").decode("unicode_escape", errors="ignore")
                text = extracted
            except Exception:
                pass
        
        # Pattern B: Strip any closed ```json ... ``` blocks containing command/args
        text = re.sub(r'```(?:json)?\s*\{\s*"command".*?\}\s*```', '', text, flags=re.DOTALL)
        # Pattern C: Strip unclosed trailing JSON blocks starting with ```json or {"command":
        text = re.sub(r'```(?:json)?\s*\{\s*"command".*$', '', text, flags=re.DOTALL)
        text = re.sub(r'\{\s*"command"\s*:\s*\{.*?$', '', text, flags=re.DOTALL)
        # Pattern D: Strip standalone closed {"command": ...}
        text = re.sub(r'\{\s*"command"\s*:\s*\{.*?\n\s*\}\s*\}', '', text, flags=re.DOTALL)

    return text.strip()

# ---------------------------------------------------------------------------
# Phil's Repos Ingestion Engine
# ---------------------------------------------------------------------------
PHIL_REPOS = [
    {
        "name": "PRIME-Moment-Attention",
        "path": os.path.join(BASE_DIR, "PRIME-Moment-Attention"),
        "focus": "Constant-state second-order recurrent attention, diagonal Taylor expansions, O(1) memory, multiscale exponential decay banks, invariant latents."
    },
    {
        "name": "PRIME-Net",
        "path": os.path.join(BASE_DIR, "PRIME-Net"),
        "focus": "Automated symbolic regression, Age-Fitness Pareto Optimization (AFPO), reverse Polish notation, discrete invariant discovery from battery & physics telemetry."
    },
    {
        "name": "mamba1and2-to-3",
        "path": os.path.join(BASE_DIR, "mamba1and2-to-3"),
        "focus": "State Space Models (SSMs), selective recurrence, Mamba-1/2 to Mamba-3 SISO architecture conversions and state tracking."
    },
    {
        "name": "prime-revisited",
        "path": os.path.join(BASE_DIR, "prime-revisited"),
        "focus": "Titan MIMO PRIME, 650M-parameter Mamba language model with discrete vote optimizer and autonomous MoE routing."
    },
    {
        "name": "Project-ThreeBody",
        "path": os.path.join(BASE_DIR, "Project-ThreeBody"),
        "focus": "Gravitational three-body problem, numerical integration, periodic orbit hunting (OrbitHunter), Poincaré sections, chaotic invariant manifolds."
    },
    {
        "name": "Project-Ramanujan",
        "path": os.path.join(BASE_DIR, "Project-Ramanujan"),
        "focus": "Polynomial Continued Fractions (PCF), automated Ramanujan machine identity mining for fundamental constants (pi, e, zeta(3), Catalan)."
    },
    {
        "name": "Project-Levitas",
        "path": os.path.join(BASE_DIR, "Project-Levitas"),
        "focus": "Voynich manuscript information theory, homophonic cipher testing, volvelle 2D gear stencils, hidden Markov models, synthetic corpus validation."
    },
    {
        "name": "Project-Kryptos",
        "path": os.path.join(BASE_DIR, "Project-Kryptos"),
        "focus": "Sanborn K4 cipher cryptanalysis, transposition lattices, keyword permutation forward solvers, swarm mining."
    },
    {
        "name": "Project-Beale",
        "path": os.path.join(BASE_DIR, "Project-Beale"),
        "focus": "Statistical cryptanalysis of Beale ciphers, information-theoretic profiling, structural asymmetry between authenticated Cipher 2 and Ciphers 1 & 3."
    },
    {
        "name": "Operating-Organism",
        "path": os.path.join(BASE_DIR, "Operating-Organism"),
        "focus": "Biological & computational organism architectures, decentralized autonomous agency, systems biology models."
    }
]

def sample_repo_context(repo_info: dict) -> str:
    path = repo_info["path"]
    if not os.path.exists(path):
        return "Repo: " + repo_info["name"] + "\nDescription: " + repo_info["focus"]
    return (
        "Repository: " + repo_info["name"] + "\n"
        "Domain Focus: " + repo_info["focus"] + "\n"
        "Key Implemented Baselines: C99 universal binary (`c/bin/prime.com`, 973 KB), "
        "Sub-byte 1-bit bipolar XNOR-popcount GEMM (42.22 GFLOPS, 128 KB matrix footprint), "
        "8-octave fractal power-law memory (tau_k = tau_0 * 2^k, >10^20x signal advantage over distractors), "
        "Non-abelian SU(2) Lie group unitary rotation (10.68M rotations/s, 0.00008768 drift), "
        "and Vectorized Dense/Chunked Parallel Attention (200x training speedup, 88,500+ tok/s)."
    )

# ---------------------------------------------------------------------------
# Internet Search Engine (GitHub & Academic Literature)
# ---------------------------------------------------------------------------
def search_github(query: str, max_results: int = 3) -> list:
    results = []
    try:
        encoded_q = urllib.parse.quote_plus(query)
        url = f"https://api.github.com/search/repositories?q={encoded_q}&sort=stars&order=desc&per_page={max_results}"
        req = urllib.request.Request(url, headers={"User-Agent": "FalconAutonomousResearcher/2.0"})
        with urllib.request.urlopen(req, timeout=8) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            for item in data.get("items", []):
                results.append({
                    "type": "github_repo",
                    "title": item.get("full_name", ""),
                    "url": item.get("html_url", ""),
                    "snippet": item.get("description", "") or "No description",
                    "stars": item.get("stargazers_count", 0)
                })
    except Exception as e:
        print(f"[-] GitHub search error for '{query}': {e}")
    return results

def search_crossref(query: str, max_results: int = 3) -> list:
    results = []
    try:
        encoded_q = urllib.parse.quote_plus(query)
        url = f"https://api.crossref.org/works?query={encoded_q}&rows={max_results}"
        req = urllib.request.Request(url, headers={"User-Agent": "FalconAutonomousResearcher/2.0 (mailto:research@example.com)"})
        with urllib.request.urlopen(req, timeout=8) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            items = data.get("message", {}).get("items", [])
            for item in items:
                titles = item.get("title", [])
                title = titles[0] if titles else "Untitled Paper"
                doi = item.get("DOI", "")
                url = f"https://doi.org/{doi}" if doi else ""
                container = item.get("container-title", ["Academic Journal"])[0] if item.get("container-title") else "Journal"
                results.append({
                    "type": "academic_paper",
                    "title": title,
                    "url": url,
                    "snippet": f"Published in {container}. Subject: {', '.join(item.get('subject', []))[:100]}"
                })
    except Exception as e:
        print(f"[-] CrossRef search error for '{query}': {e}")
    return results

# ---------------------------------------------------------------------------
# Upgraded Research Tracks with Mandatory Exact Equations
# ---------------------------------------------------------------------------
CORE_RESEARCH_TRACKS = [
    {
        "domain": "Non-Abelian Lie Group Recurrence & SU(2) Gauge Invariance (Wave 5)",
        "primary_repo": "PRIME-Moment-Attention",
        "secondary_repo": "PRIME-Net",
        "web_search": "non-abelian gauge group linear attention Lie group SO3 SU2 recurrent manifold",
        "target_formulas": ["73816 / 1024", "(4 * 64**2 + 5 * 64) * 4 / 1024"],
        "problem_prompt": """
Wave 4 successfully implemented Symplectic Hamiltonian flow and RWKV-7 curvature delta updates in C99.
How can we extend the state transition operator from abelian scalar decays to non-Abelian Lie algebra rotations in SU(2) or SO(3)?
Derive the continuous-time Wilson loop invariant around closed token loops that guarantees zero curvature drift without artificial normalization.

MANDATORY NUMERICAL EVALUATION (Section 3):
Calculate the exact memory footprint in KB of our 3-Tier Cognitive Engine (73,816 bytes): [calc: 73816 / 1024] KB.
Calculate the memory footprint for an extended SU(2) quaternionic state with D=64: [calc: (4 * 64**2 + 5 * 64) * 4 / 1024] KB.
Provide a complete, runnable C99 implementation blueprint.
"""
    },
    {
        "domain": "Sub-Byte 1-Bit XNOR-Popcount SIMD Micro-Kernels for Cosmopolitan APE",
        "primary_repo": "PRIME-Moment-Attention",
        "secondary_repo": "prime-revisited",
        "web_search": "1-bit binary neural network XNOR popcount bit-serial AVX2 NEON zero dependency C99",
        "target_formulas": ["262184 / 1024", "(10.0 * 10**9 * 1 / 8) / (1024**2)"],
        "problem_prompt": """
In Wave 4, we implemented native 1.58-bit ternary bitmask GEMM (prime_gemm_ternary.c), achieving 8x compression over FP16.
How can we extend this kernel to 1-bit binary bipolar weights (+1, -1) using native XNOR and __builtin_popcount instructions for AVX-512 and ARM NEON?
Derive the scaling and thresholding theorems that preserve Taylor attention gradient fidelity when backpropagating through discrete 1-bit linear projections.

MANDATORY NUMERICAL EVALUATION (Section 3):
Calculate the footprint in KB for our 1.58-bit ternary 1024x1024 matrix (262,184 bytes): [calc: 262184 / 1024] KB.
Calculate the total parameter size in MB for a 10B model packed at pure 1-bit (1 bit/weight): [calc: (10.0 * 10**9 * 1 / 8) / (1024**2)] MB.
Provide a complete, standalone C99 micro-kernel.
"""
    },
    {
        "domain": "Fractal Power-Law Horizons for Multi-Scale Titans GTRM Manifolds",
        "primary_repo": "PRIME-Moment-Attention",
        "secondary_repo": "PRIME-Net",
        "web_search": "power-law forgetting curve multi-scale memory bank fractal recurrent state",
        "target_formulas": ["65536 / 1024", "1.0 - 0.5**8"],
        "problem_prompt": """
Our Tier-2 GTRM episodic memory consolidates surprising thoughts into a 64 KB state manifold with discount eta=0.90.
How can we replace a single scalar discount with a multi-scale bank of power-law decays tau_k = tau_0 * 2^k across 8 fractal memory horizons?
Prove that power-law decay enables simultaneous retention of high-frequency local syntactic details and multi-million-token narrative arcs.

MANDATORY NUMERICAL EVALUATION (Section 3):
Calculate the memory in KB for our baseline Titans GTRM state (65,536 bytes): [calc: 65536 / 1024] KB.
Calculate the cumulative retention weight across 8 octaves of decay: [calc: 1.0 - 0.5**8].
Provide a complete, runnable C99 update function.
"""
    },
    {
        "domain": "Automated Lean 4 Hardware Formalization of Symplectic Flow Stability",
        "primary_repo": "PRIME-Moment-Attention",
        "secondary_repo": "PRIME-Net",
        "web_search": "Lean 4 Mathlib formalization symplectic integrator energy conservation Cayley",
        "target_formulas": ["3.567271 - 3.350956", "(3.567271 - 3.350956) / 3.567271 * 100.0"],
        "problem_prompt": """
Wave 4 verified that Symplectic Hamiltonian phase-space rotation exhibits minimal energy drift over 10,000 steps in prime.com.
How can we formally prove in Lean 4 with Mathlib that the discrete Cayley transform R(theta) = (I - J*theta/2)^(-1) (I + J*theta/2) is unconditionally isometric and strictly preserves the symplectic 2-form omega = dS1 ^ dS2?
Write a syntactically valid Lean 4 theorem and proof script.

MANDATORY NUMERICAL EVALUATION (Section 3):
Compute the exact energy drift observed in our 10,000-step benchmark (initial 3.567271, final 3.350956): [calc: 3.567271 - 3.350956].
Compute the percentage drift rate: [calc: (3.567271 - 3.350956) / 3.567271 * 100.0] %.
Provide the complete Lean 4 theorem.
"""
    },
    {
        "domain": "Information-Theoretic Capacity Bounds on 3-Tier Cognitive Hierarchy",
        "primary_repo": "PRIME-Moment-Attention",
        "secondary_repo": "prime-revisited",
        "web_search": "associative memory capacity bound Hopfield network linear attention channel capacity",
        "target_formulas": ["256 * 64 * 4 / 1024", "73816 / 1024"],
        "problem_prompt": """
Our Wave 4 3-Tier engine unifies a 256-token working memory ring buffer (64 KB) with a 64 KB Titans GTRM episodic manifold.
Derive the formal Shannon-Hopfield associative capacity limit C(W, M) in bits as a function of head dimension D=64, window size W=256, and map size d_map=32.
Prove that the error probability for needle retrieval decays exponentially with signal-to-noise ratio SNR = ||v_needle||^2 / sigma_noise^2.

MANDATORY NUMERICAL EVALUATION (Section 3):
Calculate Tier 1 buffer memory in KB: [calc: 256 * 64 * 4 / 1024] KB.
Calculate total combined 3-tier memory in KB: [calc: 73816 / 1024] KB.
Provide the full mathematical derivation and verification script.
"""
    },
    {
        "domain": "Continual Lifelong Learning & Online Test-Time Training (TTT) As It Runs",
        "primary_repo": "PRIME-Moment-Attention",
        "secondary_repo": "PRIME-Net",
        "web_search": "online test-time training continual lifelong learning catastrophic forgetting dual memory systems TTT linear attention",
        "target_formulas": ["1024 * 64 * 4 / 1024", "(1.0 - 0.0001)**10000"],
        "problem_prompt": """
Wave 5 successfully verified 1-bit bipolar XNOR GEMM, 8-octave fractal power-law memory horizons, and SU(2) isometric rotations in C99.
How can our PRIME architecture perform TRUE CONTINUAL LEARNING directly during inference as the AI runs, learning from new data without catastrophic forgetting?
Investigate:
1. Online Test-Time Training (TTT): formulating autoregressive token processing as an online self-supervised reconstruction step that continuously updates recurrent memory states.
2. Elastic Synaptic Plasticity & Online Fisher Information: penalizing parameter drift on critical foundational knowledge while allowing fluid, rapid plastic updates on new conversational or domain facts.
3. Complementary Learning Systems (CLS): multi-rate consolidation where immediate facts absorbed into the Tier 1 ring buffer and 8-octave fractal memory are continuously distilled into the slower synaptic weight projections during idle cycles.
4. Hebbian & Surprise-Modulated Plasticity: mathematically ensuring that zero updates occur on expected tokens, while highly surprising or novel information triggers localized weight adaptations.

MANDATORY NUMERICAL EVALUATION (Section 3):
Calculate the online gradient buffer memory in KB for D=64, K=1024: [calc: 1024 * 64 * 4 / 1024] KB.
Calculate the parameter retention factor under continuous regularized decay over 10,000 steps with lambda=0.0001: [calc: (1.0 - 0.0001)**10000].
Provide a complete, runnable C99 implementation blueprint for online continual learning as it runs.
"""
    },
    {
        "domain": "Hardware FLOP Maximization & Chunked Parallel Associative Scan (Wave 6)",
        "primary_repo": "PRIME-Moment-Attention",
        "secondary_repo": "PRIME-Net",
        "web_search": "chunked state space duality parallel associative scan Blelloch GPU hardware FLOP utilization FlashAttention",
        "target_formulas": ["(1024 * 1024 * 64) / (64 * 1024)", "4641.44 / 23.12"],
        "problem_prompt": """
Our training benchmark demonstrated that replacing sequential token recurrence with Chunked Parallel SSD (B=64) delivers a 200x speedup (4641 ms down to 23 ms, 88,500+ tokens/sec).
How can we extend this to a fully parallel associative prefix scan (Blelloch scan) across chunk boundaries to reach 150,000+ tokens/sec on GPUs?
Derive the mathematical associative operator (A_2, B_2) * (A_1, B_1) = (A_2 * A_1, A_2 * B_1 + B_2) for 2nd-order moment tensors under decay gamma.
Prove that critical path depth is reduced from O(L) to O(L/B + log(L/B)).

MANDATORY NUMERICAL EVALUATION (Section 3):
Calculate the parallel speedup ratio observed in our PyTorch benchmark (4641.44 ms vs 23.12 ms): [calc: 4641.44 / 23.12]x.
Calculate the chunk reduction factor for L=1024 with B=64: [calc: (1024 * 1024 * 64) / (64 * 1024)].
Provide a complete C99/Python vectorized implementation blueprint.
"""
    },
    {
        "domain": "Fused SRAM Micro-Kernels & Quantized Mixed-Precision Training (FP8/BF16)",
        "primary_repo": "PRIME-Moment-Attention",
        "secondary_repo": "prime-revisited",
        "web_search": "Triton fused attention kernel SRAM tiling FP8 BF16 mixed precision linear attention training",
        "target_formulas": ["(2 * 4096 * 4096 * 4096) / (1e12)", "(16.0 * 10**9 * 2) / (1024**3)"],
        "problem_prompt": """
Standard linear attention training is memory-bandwidth bound due to writing intermediate states S1 and S2 to VRAM/HBM.
How can we design a fused SRAM tiling kernel that keeps 2nd-order Taylor expansions and Buckingham Pi normalizers entirely in GPU registers/shared memory?
Derive the gradient scaling laws for FP8/BF16 mixed-precision training of quadratic Taylor moments to prevent underflow without costly float32 round-trips.

MANDATORY NUMERICAL EVALUATION (Section 3):
Calculate the TFLOPs required for a 4096-token sequence through a 4096-dim layer: [calc: (2 * 4096 * 4096 * 4096) / (1e12)] TFLOPs.
Calculate the VRAM footprint in GB for a 16B parameter model in BF16: [calc: (16.0 * 10**9 * 2) / (1024**3)] GB.
Provide the kernel design and mathematical proof.
"""
    },
    {
        "domain": "Hydrodynamic Information Dynamics: Bernoulli Pressure Drops & Venturi Entrainment",
        "primary_repo": "PRIME-Moment-Attention",
        "secondary_repo": "PRIME-Net",
        "web_search": "Bernoulli principle information theory fluid dynamics associative memory Venturi entrainment suction",
        "target_formulas": ["0.5 * 1.25 * 4.0**2", "100.0 * (1.0 - 0.36787944117144233)"],
        "problem_prompt": """
In fluid mechanics, Bernoulli's principle states that along an informational streamline, an increase in velocity creates a simultaneous drop in static pressure: P + 0.5 * rho * v^2 = C. This generates a Venturi vacuum that entrains and drags adjacent fluid.
How can we mathematically map this hydrodynamic principle to high-velocity information injection in recurrent 2nd-order Taylor moment attention?
1. Define Information Velocity v_t = ||k_t - mu_context||_2 * (1.0 + Delta_t) and Information Density rho = Tr(Fisher_Information).
2. Derive the Bernoulli Informational Vacuum Delta P_t = 0.5 * rho * v_t^2, and prove that high-surprise injections collapse the activation energy barrier for semantically adjacent memory clusters.
3. Formulate the Venturi Entrainment Operator F_drag = rho * (k_inj^T k_stored) * v_t, demonstrating that injecting a novel anchor fact drags correlated background memories into active working state without brute-force search.

MANDATORY NUMERICAL EVALUATION (Section 3):
Calculate the Bernoulli dynamic pressure drop Delta P for rho=1.25, v=4.0: [calc: 0.5 * 1.25 * 4.0**2].
Calculate the entrainment suction percentage for exponent tau_p=1.0: [calc: 100.0 * (1.0 - 0.36787944117144233)] %.
Provide a complete, standalone C99/Python implementation blueprint for a VenturiEntrainmentGate.
"""
    },
    {
        "domain": "Unitary Information Conservation, Neural Spin-Echo & Spectral Deconvolution",
        "primary_repo": "PRIME-Moment-Attention",
        "secondary_repo": "PRIME-Net",
        "web_search": "quantum information conservation no-hiding theorem spin echo adjoint time reversal linear attention deconvolution",
        "target_formulas": ["2.0**(-24)", "-16.635532 / (-0.0050125)"],
        "problem_prompt": """
By the No-Hiding Theorem and quantum unitarity (U^dagger U = I), information cannot be destroyed; in recurrent neural states S_t = sum_{j=1}^t lambda^{t-j} k_j v_j^T, 'overwritten' memories are not erased, but attenuated and superposed across higher-order tensor coordinates.
1. Formulate the Adjoint Time-Reversal Operator (Neural Spin Echo): S_{j-1} = (1 / lambda) * (S_j - k_j v_j^T) to demonstrate exact historical state reconstruction in reverse time with drift < 1e-4.
2. Derive the Dual-Basis Moore-Penrose Spectral Deconvolution Operator V_recovered = (K_attenuated^dagger)^T S_T to extract historical facts directly from compressed recurrent matrices S_T with 1.000000 cosine similarity.
3. Calculate the Numerical Landauer Event Horizon: the exact number of tokens tau_crit before exponential decay lambda^tau drops below IEEE-754 float32 machine epsilon (2^-24 = 5.96e-8).
4. Prove that in a 2nd-order moment manifold S_2 in R^{D x D}, the D^2 orthogonal channels delay subspace collision by a factor of D over standard linear vectors.

MANDATORY NUMERICAL EVALUATION (Section 3):
Calculate IEEE-754 float32 single-precision machine epsilon (2^-24): [calc: 2.0**(-24)].
Calculate the exact token horizon limit tau_crit for decay lambda=0.995 before signal hits float32 epsilon: [calc: -16.635532 / (-0.0050125)].
Provide a complete, standalone C99/Python implementation blueprint for an AdjointSpinEchoMemoryRecoverer.
"""
    }
]

# ---------------------------------------------------------------------------
# Socratic Inquiry & Clarification Engine
# ---------------------------------------------------------------------------
def answer_pending_socratic_inquiries(model, tokenizer, cothinker):
    """
    Checks for pending mathematical inquiries from the Student Model (PRIME-125M).
    Generates step-by-step cognitive derivations with <think> traces using DeepSeek-R1,
    verifies arithmetic symbolically with PRIME-Net, and writes clarifications to the vault.
    """
    try:
        conn = sqlite3.connect(DB_FILE)
        cur = conn.cursor()
        cur.execute("""
            SELECT id, cycle, question_text, context_snippet 
            FROM socratic_inquiries 
            WHERE status = 'PENDING' 
            ORDER BY id ASC LIMIT 1
        """)
        row = cur.fetchone()
        if not row:
            conn.close()
            return
            
        inquiry_id, inq_cycle, question_text, context_snippet = row
        print(f"\n[?] >>> TEACHER SOCRATIC MENTORSHIP: Addressing Student Inquiry #{inquiry_id} (Cycle {inq_cycle}) <<<")
        print(f"    Question: {question_text}")
        print(f"    Context:  {context_snippet[:120]}...")
        
        system_prompt = (
            "You are the Lead Theoretical Architect and Teacher (DeepSeek-R1-Distill-14B). "
            "Your apprentice model (PRIME-125M) is studying your theoretical papers and needs guidance. "
            "First, engage in your step-by-step cognitive reasoning inside <think>...</think>, analyzing the exact mathematical derivation and intuitive physics. "
            "Then, provide the complete, crystal-clear derivation with explicit intermediate steps so the student can absorb the exact reasoning trajectory."
        )
        user_prompt = (
            f"Regarding Research Paper Cycle {inq_cycle}:\n"
            f"Context Snippet:\n\"{context_snippet}\"\n\n"
            f"Student Question:\n\"{question_text}\"\n\n"
            "Please provide a rigorous mathematical derivation and clear physical intuition to clarify this concept."
        )
        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ]
        if hasattr(tokenizer, "apply_chat_template") and tokenizer.chat_template:
            prompt_text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
        else:
            prompt_text = f"System: {system_prompt}\nUser: {user_prompt}\nAssistant: <think>\n"
            
        inputs = tokenizer(prompt_text, return_tensors="pt", max_length=1280, truncation=True).to(DEVICE)
        with torch.no_grad():
            out = model.generate(
                **inputs,
                max_new_tokens=450,
                temperature=0.6,
                top_p=0.95,
                do_sample=True
            )
        raw_ans = tokenizer.decode(out[0][inputs.input_ids.shape[1]:], skip_special_tokens=True).strip()
        del inputs, out
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
            
        clean_ans = sanitize_output(raw_ans)
        verified_ans, _ = cothinker.intercept_and_solve(clean_ans)
        
        cur.execute("""
            UPDATE socratic_inquiries 
            SET teacher_response = ?, status = 'ANSWERED' 
            WHERE id = ?
        """, (verified_ans, inquiry_id))
        conn.commit()
        conn.close()
        print(f"[+] Socratic Clarification generated ({len(verified_ans)} chars) and recorded in SQLite!")
        
        with open(DOSSIER_FILE, "a", encoding="utf-8") as f:
            f.write(f"\n### Socratic Clarification for Student (Inquiry #{inquiry_id} on Cycle {inq_cycle})\n\n")
            f.write(f"**Student Inquiry**: *{question_text}*\n\n")
            f.write(f"**Teacher Response & Derivation**:\n\n{verified_ans}\n\n---\n\n")
    except Exception as e:
        print(f"[-] Error answering socratic inquiry: {e}")

# ---------------------------------------------------------------------------
# Main Autonomous Loop v2.0
# ---------------------------------------------------------------------------
def run_autonomous_research_loop():
    track_idx = telemetry.theories_count
    cycle = telemetry.theories_count + 1
    
    print("\n" + "=" * 80)
    print("      FALCON3-10B-1.58BIT AUTONOMOUS RESEARCH DAEMON v2.0 (UPGRADED)")
    print("=" * 80 + "\n")
    
    while True:
        try:
            track = CORE_RESEARCH_TRACKS[track_idx % len(CORE_RESEARCH_TRACKS)]
            domain = track["domain"]
            primary_repo_name = track["primary_repo"]
            secondary_repo_name = track["secondary_repo"]
            web_query = track["web_search"]
            problem_prompt = track["problem_prompt"].strip()
            
            topic_title = f"{domain}: Cycle {cycle}"
            telemetry.update("STUDYING_REPOS", domain, topic_title, cycle)
            print(f"\n[{time.strftime('%X')}] === STARTING RESEARCH CYCLE {cycle} ===")
            print(f"[*] Target Domain: {domain}")
            print(f"[*] Target Repos: {primary_repo_name} & {secondary_repo_name}")
            
            primary_repo = next((r for r in PHIL_REPOS if r["name"] == primary_repo_name), None)
            secondary_repo = next((r for r in PHIL_REPOS if r["name"] == secondary_repo_name), None)
            
            repo_context = ""
            if primary_repo:
                repo_context += sample_repo_context(primary_repo) + "\n\n"
            if secondary_repo:
                repo_context += sample_repo_context(secondary_repo)
            telemetry.repos_studied += 2
            
            telemetry.update("SEARCHING_WEB", domain, topic_title, cycle)
            print(f"[*] Querying Internet for: '{web_query}'...")
            gh_results = search_github(web_query, max_results=2)
            crossref_results = search_crossref(web_query, max_results=2)
            all_literature = gh_results + crossref_results
            telemetry.papers_ingested += len(all_literature)
            
            lit_summary = ""
            for item in all_literature:
                lit_summary += f"- [{item['type'].upper()}] {item['title']} ({item.get('url', '')}): {item['snippet']}\n"
                try:
                    conn = sqlite3.connect(DB_FILE)
                    cur = conn.cursor()
                    cur.execute("""
                    INSERT INTO literature (cycle, timestamp, source_type, title, url, snippet)
                    VALUES (?, ?, ?, ?, ?, ?)
                    """, (cycle, time.strftime("%Y-%m-%d %H:%M:%S"), item["type"], item["title"], item.get("url", ""), item["snippet"]))
                    conn.commit()
                    conn.close()
                except Exception:
                    pass
                    
            print(f"[+] Retrieved {len(all_literature)} relevant external resources.")
            
            # Step 3: Upgraded Deep Formulation
            telemetry.update("THINKING", domain, topic_title, cycle)
            print(f"[*] Prompting Falcon3-10B-1.58bit with anti-leakage constraints & mandatory quantitative tags...")
            
            system_prompt = (
                "You are an elite theoretical physicist, sequence model architect, and applied mathematician. "
                "You are writing formal research papers in Phil's laboratory.\n\n"
                "CRITICAL FORMAT RULES (STRICT):\n"
                "1. NEVER emit JSON commands, tool calls, or schemas (e.g. NEVER write '{\"command\": ...}', 'write_to_file', or 'browse_website'). Write directly in standard technical Markdown.\n"
                "2. Reason through the problem inside <think>...</think>.\n"
                "3. Structure each paper into these 4 sections:\n"
                "   # Theoretical Formulation & Core Thesis\n"
                "   ## Mathematical Derivations & State Transitions\n"
                "   ## Quantitative Numerical Benchmarks: Compute every requested value inside [calc: <formula>] or <<formula>> tags so PRIME-Net can symbolically verify it (e.g. [calc: 32 * 512 * 4]).\n"
                "   ## Implementation & Verification Blueprint (Python / C99)\n"
                "4. Provide non-circular, mathematically rigorous theorems with precise bounds.\n"
                "5. Provide a complete, runnable Python or C99 verification implementation in markdown codeblocks."
            )
            
            user_prompt = f"""
=== FRONTIER RESEARCH CHALLENGE ===
Domain: {domain}
Primary Repository: {primary_repo_name}
Secondary Repository: {secondary_repo_name}

{problem_prompt}

=== EXTERNAL LITERATURE & CODE DISCOVERED ===
{lit_summary}

=== LOCAL REPOSITORY CONTEXT ===
{repo_context}
"""
            messages = [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ]
            
            if hasattr(tokenizer, "apply_chat_template") and tokenizer.chat_template:
                prompt_text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
            else:
                prompt_text = f"System: {system_prompt}\nUser: {user_prompt}\nAssistant: <think>\n"
                
            inputs = tokenizer(prompt_text, return_tensors="pt", max_length=1280, truncation=True).to(DEVICE)
            
            telemetry.update("THINKING", domain, topic_title, cycle, live_thought="Synthesizing rigorous mathematical derivation and C99 blueprints...")
            print(f"[*] Generating theoretical formulation with DeepSeek-R1-Distill-14B (prompt: {inputs.input_ids.shape[1]} tokens, max 1000 tokens)...")
            gen_start = time.time()
            with torch.no_grad():
                out = model.generate(
                    **inputs,
                    max_new_tokens=1000,
                    temperature=0.6,
                    top_p=0.95,
                    do_sample=True
                )
            gen_duration = time.time() - gen_start
            raw_response = tokenizer.decode(out[0][inputs.input_ids.shape[1]:], skip_special_tokens=True).strip()
            print(f"[+] Generation finished in {gen_duration:.2f}s ({len(raw_response)} chars).")
            del inputs, out
            if torch.cuda.is_available():
                torch.cuda.empty_cache()
            
            # Sanitize output (removes any accidental JSON schema leakage)
            clean_response = sanitize_output(raw_response)
            
            # Step 4: PRIME-Net Symbolic Verification
            telemetry.update("VERIFYING", domain, topic_title, cycle, live_thought=clean_response)
            verified_response, injections = cothinker.intercept_and_solve(clean_response, target_formulas=track.get("target_formulas"))
            
            telemetry.formulas_verified += len(injections)
            if injections:
                telemetry.last_formula = f"{injections[0]['expr']} = {injections[0]['result']}"
                print(f"[+] PRIME-Net verified {len(injections)} formulas symbolically in microseconds!")
                for inj in injections:
                    print(f"    - {inj['expr']} = {inj['result']}")
            else:
                print(f"[-] Note: 0 formulas caught by <<...>> pattern.")
                
            # Extract summary & thought
            thought_match = re.search(r"<think>(.*?)</think>", clean_response, re.DOTALL)
            thought_trace = thought_match.group(1).strip() if thought_match else clean_response[:400]
            summary_text = re.sub(r"<think>.*?</think>", "", verified_response, flags=re.DOTALL).strip()
            if not summary_text:
                summary_text = verified_response[:600]
                
            # Step 5: Save Theory to Knowledge Vault
            telemetry.theories_count += 1
            telemetry.last_theory_title = f"Cycle {cycle}: {domain}"
            telemetry.update("SAVING", domain, topic_title, cycle, live_thought=clean_response)
            
            # Record in SQLite
            try:
                conn = sqlite3.connect(DB_FILE)
                cur = conn.cursor()
                cur.execute("""
                INSERT INTO theories (cycle, timestamp, domain, topic, summary, thought_trace, verified_equations, code_solution, external_sources)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
                """, (
                    cycle,
                    time.strftime("%Y-%m-%d %H:%M:%S"),
                    domain,
                    topic_title,
                    summary_text[:1500],
                    thought_trace[:4000],
                    json.dumps(injections),
                    summary_text,
                    json.dumps([item["title"] for item in all_literature])
                ))
                conn.commit()
                conn.close()
            except Exception as e:
                print(f"[-] SQLite insertion error: {e}")
                
            # Record in Markdown Dossier
            with open(DOSSIER_FILE, "a", encoding="utf-8") as f:
                f.write(f"## Cycle {cycle}: {domain}\n\n")
                f.write(f"**Timestamp**: {time.strftime('%Y-%m-%d %H:%M:%S')}  \n")
                f.write(f"**Synthesized Repos**: `{primary_repo_name}` & `{secondary_repo_name}`  \n")
                f.write(f"**External Literature Found**: {len(all_literature)} sources  \n")
                if injections:
                    f.write(f"**PRIME-Net Verifications**: {len(injections)} formulas verified symbolically  \n")
                    for inj in injections:
                        f.write(f"  - `{inj['expr']}` = **`{inj['result']}`**\n")
                f.write("\n### Deep Cognitive Thought Trace\n")
                f.write(f"```text\n{thought_trace[:2500]}\n```\n\n")
                f.write("### Formulated Theory & Solution Blueprint\n\n")
                f.write(f"{summary_text}\n\n")
                f.write("---\n\n")
                
            print(f"[+] Cycle {cycle} complete! Theory saved to {DOSSIER_FILE}")
            
            # Step 5b: Socratic Mentorship of Student Model (PRIME-125M)
            answer_pending_socratic_inquiries(model, tokenizer, cothinker)
            
            # Step 6: Advance & Cleanup
            cycle += 1
            track_idx += 1
            
            if torch.cuda.is_available():
                torch.cuda.empty_cache()
                
            time.sleep(5)
            
        except Exception as e:
            print(f"[!] Exception in research cycle: {e}")
            traceback.print_exc()
            if torch.cuda.is_available():
                torch.cuda.empty_cache()
            time.sleep(10)
            track_idx += 1

if __name__ == "__main__":
    run_autonomous_research_loop()
