#!/usr/bin/env python3
"""
Falcon-10B-1.58bit Autonomous Research Daemon (PRIME-Scout Core v2.0)
=====================================================================
Upgraded with:
  1. Anti-Tool-Leakage Filters & Pure Markdown Publication Synthesis
  2. Guaranteed Quantitative Invariant Benchmarking (100% PRIME-Net Execution)
  3. Non-Tautological Mathematical Rigor & Standalone Verification Code
  4. Real-Time Internet Search (GitHub API & CrossRef Scholarly Discovery)
  5. Continuous Thought & Formulation Engine (never goes idle)
  6. Live Telemetry Streamer & SQLite Knowledge Vault
"""

import os
import sys
import time
import json
import sqlite3
import re
import urllib.request
import urllib.parse
import traceback
import psutil

# Ensure scratch Triton directories
scratch_dir = "/home/phil/.gemini/antigravity/scratch/.triton"
os.environ["TRITON_HOME"] = scratch_dir
os.environ["TRITON_CACHE_DIR"] = os.path.join(scratch_dir, "cache")
os.environ["TORCHINDUCTOR_CACHE_DIR"] = os.path.join(scratch_dir, "inductor")
os.environ["TORCH_EXTENSIONS_DIR"] = os.path.join(scratch_dir, "extensions")
os.makedirs(os.environ["TRITON_CACHE_DIR"], exist_ok=True)
os.makedirs(os.environ["TORCHINDUCTOR_CACHE_DIR"], exist_ok=True)
os.makedirs(os.environ["TORCH_EXTENSIONS_DIR"], exist_ok=True)

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, TextStreamer
from prime_moment_attention.primenet_cothinker_bridge import PrimeNetCoThinker

# Paths
BASE_DIR = "/home/phil/.gemini/antigravity/scratch"
REPO_DIR = os.path.join(BASE_DIR, "PRIME-Moment-Attention")
VAULT_DIR = os.path.join(REPO_DIR, "research_vault")
os.makedirs(VAULT_DIR, exist_ok=True)

STATUS_FILE = os.path.join(VAULT_DIR, "live_status.json")
DB_FILE = os.path.join(VAULT_DIR, "research_vault.sqlite3")
DOSSIER_FILE = os.path.join(VAULT_DIR, "THEORY_DOSSIER.md")

SNAPSHOT_PATH = "/home/phil/.cache/huggingface/hub/models--tiiuae--Falcon3-10B-Instruct-1.58bit/snapshots/4b61e8876b19bf7a4b271b757a1bd2974bf38913"
MODEL_ID = SNAPSHOT_PATH if os.path.isdir(SNAPSHOT_PATH) else "tiiuae/Falcon3-10B-Instruct-1.58bit"
DEVICE = "cuda:0" if torch.cuda.is_available() else "cpu"

print(f"[*] Initializing Autonomous Research Daemon v2.0 on {DEVICE}...")
print(f"[*] Vault Directory: {VAULT_DIR}")

# ---------------------------------------------------------------------------
# Database Setup
# ---------------------------------------------------------------------------
def init_db():
    conn = sqlite3.connect(DB_FILE)
    cur = conn.cursor()
    cur.execute("""
    CREATE TABLE IF NOT EXISTS theories (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        cycle INTEGER,
        timestamp TEXT,
        domain TEXT,
        topic TEXT,
        summary TEXT,
        thought_trace TEXT,
        verified_equations TEXT,
        code_solution TEXT,
        external_sources TEXT
    )
    """)
    cur.execute("""
    CREATE TABLE IF NOT EXISTS literature (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        cycle INTEGER,
        timestamp TEXT,
        source_type TEXT,
        title TEXT,
        url TEXT,
        snippet TEXT
    )
    """)
    conn.commit()
    conn.close()

init_db()

# ---------------------------------------------------------------------------
# Dossier Header Setup
# ---------------------------------------------------------------------------
if not os.path.exists(DOSSIER_FILE):
    with open(DOSSIER_FILE, "w", encoding="utf-8") as f:
        f.write("# Autonomous Theoretical Research Dossier\n")
        f.write("### Generated by Falcon3-10B-Instruct-1.58bit + PRIME-Net Symbolic Co-Thinker\n\n")
        f.write("An ongoing, autonomous scientific discovery record synthesizing Phil (@batteryphil)'s research universe with state-of-the-art open literature and code.\n\n")
        f.write("---\n\n")

# ---------------------------------------------------------------------------
# Telemetry Helper
# ---------------------------------------------------------------------------
class TelemetryManager:
    def __init__(self):
        self.start_time = time.time()
        self.theories_count = 0
        self.repos_studied = 0
        self.papers_ingested = 0
        self.formulas_verified = 0
        self.last_theory_title = "Initializing..."
        self.last_formula = "None"
        
        # Load existing counters from DB if present
        try:
            conn = sqlite3.connect(DB_FILE)
            cur = conn.cursor()
            cur.execute("SELECT COUNT(*) FROM theories")
            self.theories_count = cur.fetchone()[0]
            cur.execute("SELECT COUNT(*) FROM literature")
            self.papers_ingested = cur.fetchone()[0]
            conn.close()
        except Exception:
            pass
        
    def update(self, status: str, domain: str, topic: str, cycle: int, live_thought: str = ""):
        uptime = int(time.time() - self.start_time)
        vram_alloc = torch.cuda.memory_allocated() / (1024**3) if torch.cuda.is_available() else 0.0
        vram_total = torch.cuda.get_device_properties(0).total_memory / (1024**3) if torch.cuda.is_available() else 0.0
        
        vm = psutil.virtual_memory()
        ram_used = (vm.total - vm.available) / (1024**3)
        ram_total = vm.total / (1024**3)
        cpu_pct = psutil.cpu_percent(interval=None)
        
        data = {
            "status": status,
            "cycle": cycle,
            "domain": domain,
            "topic": topic,
            "uptime_seconds": uptime,
            "pid": os.getpid(),
            "vram_allocated_gb": round(vram_alloc, 2),
            "vram_total_gb": round(vram_total, 2),
            "ram_used_gb": round(ram_used, 2),
            "ram_total_gb": round(ram_total, 2),
            "cpu_percent": cpu_pct,
            "live_thought_snippet": live_thought[-600:] if live_thought else "",
            "total_theories_generated": self.theories_count,
            "total_repos_studied": self.repos_studied,
            "total_papers_ingested": self.papers_ingested,
            "total_formulas_verified": self.formulas_verified,
            "last_theory_title": self.last_theory_title,
            "last_verified_formula": self.last_formula,
            "timestamp": time.strftime("%Y-%m-%d %H:%M:%S")
        }
        
        tmp_file = STATUS_FILE + ".tmp"
        with open(tmp_file, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2)
        os.replace(tmp_file, STATUS_FILE)

telemetry = TelemetryManager()
telemetry.update("INITIALIZING_MODEL", "System", "Loading Falcon3-10B-1.58bit", telemetry.theories_count + 1)

# ---------------------------------------------------------------------------
# Model & PRIME-Net Co-Thinker Initialization
# ---------------------------------------------------------------------------
print(f"[*] Loading Tokenizer & Weights for {MODEL_ID} on {DEVICE}...")
is_local = os.path.isdir(MODEL_ID)
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, trust_remote_code=True, local_files_only=is_local)
model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    torch_dtype=torch.bfloat16,
    device_map=DEVICE,
    trust_remote_code=True,
    local_files_only=is_local
)
model.eval()

cothinker = PrimeNetCoThinker()
vram_boot = torch.cuda.memory_allocated() / (1024**3) if torch.cuda.is_available() else 0.0
print(f"[+] Model loaded successfully! VRAM: {vram_boot:.2f} GB")
telemetry.update("MODEL_READY", "System", "Model loaded in VRAM", telemetry.theories_count + 1)

# ---------------------------------------------------------------------------
# Streaming Callback for Live Monitor Telemetry
# ---------------------------------------------------------------------------
class LiveThoughtStreamer(TextStreamer):
    def __init__(self, tokenizer, on_token_cb, **kwargs):
        super().__init__(tokenizer, **kwargs)
        self.on_token_cb = on_token_cb
        self.accumulated = ""
        self.last_update = 0.0

    def on_finalized_text(self, text: str, stream_end: bool = False):
        self.accumulated += text
        now = time.time()
        if now - self.last_update > 0.8 or stream_end:
            self.last_update = now
            if self.on_token_cb:
                self.on_token_cb(self.accumulated, stream_end)

# ---------------------------------------------------------------------------
# Sanitization Helper (Anti-Tool-Leakage)
# ---------------------------------------------------------------------------
def sanitize_output(text: str) -> str:
    """Eliminates accidental JSON tool-calling schemas and extracts genuine markdown."""
    for token in ['<|assistant|>', '<|user|>', '<|system|>', '<tool_call>', '</tool_call>', '<tool_response>', '</tool_response>']:
        text = text.replace(token, '')

    if '"command":' in text or '"name":' in text:
        # Pattern A: Wrapped in write_to_file
        m = re.search(r'\{\s*"command"\s*:\s*\{.*?"args"\s*:\s*\{.*?"text"\s*:\s*"(.*?)"\s*\}\s*\}\s*\}', text, re.DOTALL)
        if m:
            try:
                extracted = m.group(1).encode("utf-8").decode("unicode_escape", errors="ignore")
                text = extracted
            except Exception:
                pass
        
        # Pattern B: Strip any closed ```json ... ``` blocks containing command/args
        text = re.sub(r'```(?:json)?\s*\{\s*"command".*?\}\s*```', '', text, flags=re.DOTALL)
        # Pattern C: Strip unclosed trailing JSON blocks starting with ```json or {"command":
        text = re.sub(r'```(?:json)?\s*\{\s*"command".*$', '', text, flags=re.DOTALL)
        text = re.sub(r'\{\s*"command"\s*:\s*\{.*?$', '', text, flags=re.DOTALL)
        # Pattern D: Strip standalone closed {"command": ...}
        text = re.sub(r'\{\s*"command"\s*:\s*\{.*?\n\s*\}\s*\}', '', text, flags=re.DOTALL)

    return text.strip()

# ---------------------------------------------------------------------------
# Phil's Repos Ingestion Engine
# ---------------------------------------------------------------------------
PHIL_REPOS = [
    {
        "name": "PRIME-Moment-Attention",
        "path": os.path.join(BASE_DIR, "PRIME-Moment-Attention"),
        "focus": "Constant-state second-order recurrent attention, diagonal Taylor expansions, O(1) memory, multiscale exponential decay banks, invariant latents."
    },
    {
        "name": "PRIME-Net",
        "path": os.path.join(BASE_DIR, "PRIME-Net"),
        "focus": "Automated symbolic regression, Age-Fitness Pareto Optimization (AFPO), reverse Polish notation, discrete invariant discovery from battery & physics telemetry."
    },
    {
        "name": "mamba1and2-to-3",
        "path": os.path.join(BASE_DIR, "mamba1and2-to-3"),
        "focus": "State Space Models (SSMs), selective recurrence, Mamba-1/2 to Mamba-3 SISO architecture conversions and state tracking."
    },
    {
        "name": "prime-revisited",
        "path": os.path.join(BASE_DIR, "prime-revisited"),
        "focus": "Titan MIMO PRIME, 650M-parameter Mamba language model with discrete vote optimizer and autonomous MoE routing."
    },
    {
        "name": "Project-ThreeBody",
        "path": os.path.join(BASE_DIR, "Project-ThreeBody"),
        "focus": "Gravitational three-body problem, numerical integration, periodic orbit hunting (OrbitHunter), Poincaré sections, chaotic invariant manifolds."
    },
    {
        "name": "Project-Ramanujan",
        "path": os.path.join(BASE_DIR, "Project-Ramanujan"),
        "focus": "Polynomial Continued Fractions (PCF), automated Ramanujan machine identity mining for fundamental constants (pi, e, zeta(3), Catalan)."
    },
    {
        "name": "Project-Levitas",
        "path": os.path.join(BASE_DIR, "Project-Levitas"),
        "focus": "Voynich manuscript information theory, homophonic cipher testing, volvelle 2D gear stencils, hidden Markov models, synthetic corpus validation."
    },
    {
        "name": "Project-Kryptos",
        "path": os.path.join(BASE_DIR, "Project-Kryptos"),
        "focus": "Sanborn K4 cipher cryptanalysis, transposition lattices, keyword permutation forward solvers, swarm mining."
    },
    {
        "name": "Project-Beale",
        "path": os.path.join(BASE_DIR, "Project-Beale"),
        "focus": "Statistical cryptanalysis of Beale ciphers, information-theoretic profiling, structural asymmetry between authenticated Cipher 2 and Ciphers 1 & 3."
    },
    {
        "name": "Operating-Organism",
        "path": os.path.join(BASE_DIR, "Operating-Organism"),
        "focus": "Biological & computational organism architectures, decentralized autonomous agency, systems biology models."
    }
]

def sample_repo_context(repo_info: dict) -> str:
    path = repo_info["path"]
    if not os.path.exists(path):
        return f"Repo: {repo_info['name']}\nDescription: {repo_info['focus']}"
    
    snippets = []
    snippets.append(f"Repository: {repo_info['name']}")
    snippets.append(f"Domain Focus: {repo_info['focus']}")
    
    # Priority inspection files: C99 headers, Wave 1-4 implementation, and README
    key_files = [
        "c/README.md", "c/prime_moment.h", "c/prime_gtrm.h", "c/prime_gemm_ternary.h",
        "c/prime_tier.h", "c/prime_buckingham.h",
        "prime_moment_attention/prime_attention.py", "buckingham_pi.py", "prime_core.py",
        "HarmonicOscillatorInvariant.lean"
    ]
    for rel_path in key_files:
        full_path = os.path.join(path, rel_path)
        if os.path.exists(full_path):
            try:
                with open(full_path, "r", encoding="utf-8", errors="ignore") as f:
                    content = f.read()[:1200]
                    snippets.append(f"Source Code Sample ({rel_path}):\n{content}")
            except Exception:
                pass
                
    readme_path = os.path.join(path, "README.md")
    if os.path.exists(readme_path):
        try:
            with open(readme_path, "r", encoding="utf-8", errors="ignore") as f:
                lines = f.readlines()[:40]
                snippets.append("Root README Sample:\n" + "".join(lines))
        except Exception:
            pass
            
    py_files = [f for f in os.listdir(path) if f.endswith(".py") and not f.startswith(".")][:2]
    for py_file in py_files:
        p = os.path.join(path, py_file)
        try:
            with open(p, "r", encoding="utf-8", errors="ignore") as f:
                content = f.read()[:600]
                snippets.append(f"Python Module ({py_file}):\n{content}")
        except Exception:
            pass
            
    return "\n---\n".join(snippets)

# ---------------------------------------------------------------------------
# Internet Search Engine (GitHub & Academic Literature)
# ---------------------------------------------------------------------------
def search_github(query: str, max_results: int = 3) -> list:
    results = []
    try:
        encoded_q = urllib.parse.quote_plus(query)
        url = f"https://api.github.com/search/repositories?q={encoded_q}&sort=stars&order=desc&per_page={max_results}"
        req = urllib.request.Request(url, headers={"User-Agent": "FalconAutonomousResearcher/2.0"})
        with urllib.request.urlopen(req, timeout=8) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            for item in data.get("items", []):
                results.append({
                    "type": "github_repo",
                    "title": item.get("full_name", ""),
                    "url": item.get("html_url", ""),
                    "snippet": item.get("description", "") or "No description",
                    "stars": item.get("stargazers_count", 0)
                })
    except Exception as e:
        print(f"[-] GitHub search error for '{query}': {e}")
    return results

def search_crossref(query: str, max_results: int = 3) -> list:
    results = []
    try:
        encoded_q = urllib.parse.quote_plus(query)
        url = f"https://api.crossref.org/works?query={encoded_q}&rows={max_results}"
        req = urllib.request.Request(url, headers={"User-Agent": "FalconAutonomousResearcher/2.0 (mailto:research@example.com)"})
        with urllib.request.urlopen(req, timeout=8) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            items = data.get("message", {}).get("items", [])
            for item in items:
                titles = item.get("title", [])
                title = titles[0] if titles else "Untitled Paper"
                doi = item.get("DOI", "")
                url = f"https://doi.org/{doi}" if doi else ""
                container = item.get("container-title", ["Academic Journal"])[0] if item.get("container-title") else "Journal"
                results.append({
                    "type": "academic_paper",
                    "title": title,
                    "url": url,
                    "snippet": f"Published in {container}. Subject: {', '.join(item.get('subject', []))[:100]}"
                })
    except Exception as e:
        print(f"[-] CrossRef search error for '{query}': {e}")
    return results

# ---------------------------------------------------------------------------
# Upgraded Research Tracks with Mandatory Exact Equations
# ---------------------------------------------------------------------------
CORE_RESEARCH_TRACKS = [
    {
        "domain": "Non-Abelian Lie Group Recurrence & SU(2) Gauge Invariance (Wave 5)",
        "primary_repo": "PRIME-Moment-Attention",
        "secondary_repo": "PRIME-Net",
        "web_search": "non-abelian gauge group linear attention Lie group SO3 SU2 recurrent manifold",
        "target_formulas": ["73816 / 1024", "(4 * 64**2 + 5 * 64) * 4 / 1024"],
        "problem_prompt": """
Wave 4 successfully implemented Symplectic Hamiltonian flow and RWKV-7 curvature delta updates in C99.
How can we extend the state transition operator from abelian scalar decays to non-Abelian Lie algebra rotations in SU(2) or SO(3)?
Derive the continuous-time Wilson loop invariant around closed token loops that guarantees zero curvature drift without artificial normalization.

MANDATORY NUMERICAL EVALUATION (Section 3):
Calculate the exact memory footprint in KB of our 3-Tier Cognitive Engine (73,816 bytes): [calc: 73816 / 1024] KB.
Calculate the memory footprint for an extended SU(2) quaternionic state with D=64: [calc: (4 * 64**2 + 5 * 64) * 4 / 1024] KB.
Provide a complete, runnable C99 implementation blueprint.
"""
    },
    {
        "domain": "Sub-Byte 1-Bit XNOR-Popcount SIMD Micro-Kernels for Cosmopolitan APE",
        "primary_repo": "PRIME-Moment-Attention",
        "secondary_repo": "prime-revisited",
        "web_search": "1-bit binary neural network XNOR popcount bit-serial AVX2 NEON zero dependency C99",
        "target_formulas": ["262184 / 1024", "(10.0 * 10**9 * 1 / 8) / (1024**2)"],
        "problem_prompt": """
In Wave 4, we implemented native 1.58-bit ternary bitmask GEMM (prime_gemm_ternary.c), achieving 8x compression over FP16.
How can we extend this kernel to 1-bit binary bipolar weights (+1, -1) using native XNOR and __builtin_popcount instructions for AVX-512 and ARM NEON?
Derive the scaling and thresholding theorems that preserve Taylor attention gradient fidelity when backpropagating through discrete 1-bit linear projections.

MANDATORY NUMERICAL EVALUATION (Section 3):
Calculate the footprint in KB for our 1.58-bit ternary 1024x1024 matrix (262,184 bytes): [calc: 262184 / 1024] KB.
Calculate the total parameter size in MB for a 10B model packed at pure 1-bit (1 bit/weight): [calc: (10.0 * 10**9 * 1 / 8) / (1024**2)] MB.
Provide a complete, standalone C99 micro-kernel.
"""
    },
    {
        "domain": "Fractal Power-Law Horizons for Multi-Scale Titans GTRM Manifolds",
        "primary_repo": "PRIME-Moment-Attention",
        "secondary_repo": "PRIME-Net",
        "web_search": "power-law forgetting curve multi-scale memory bank fractal recurrent state",
        "target_formulas": ["65536 / 1024", "1.0 - 0.5**8"],
        "problem_prompt": """
Our Tier-2 GTRM episodic memory consolidates surprising thoughts into a 64 KB state manifold with discount eta=0.90.
How can we replace a single scalar discount with a multi-scale bank of power-law decays tau_k = tau_0 * 2^k across 8 fractal memory horizons?
Prove that power-law decay enables simultaneous retention of high-frequency local syntactic details and multi-million-token narrative arcs.

MANDATORY NUMERICAL EVALUATION (Section 3):
Calculate the memory in KB for our baseline Titans GTRM state (65,536 bytes): [calc: 65536 / 1024] KB.
Calculate the cumulative retention weight across 8 octaves of decay: [calc: 1.0 - 0.5**8].
Provide a complete, runnable C99 update function.
"""
    },
    {
        "domain": "Automated Lean 4 Hardware Formalization of Symplectic Flow Stability",
        "primary_repo": "PRIME-Moment-Attention",
        "secondary_repo": "PRIME-Net",
        "web_search": "Lean 4 Mathlib formalization symplectic integrator energy conservation Cayley",
        "target_formulas": ["3.567271 - 3.350956", "(3.567271 - 3.350956) / 3.567271 * 100.0"],
        "problem_prompt": """
Wave 4 verified that Symplectic Hamiltonian phase-space rotation exhibits minimal energy drift over 10,000 steps in prime.com.
How can we formally prove in Lean 4 with Mathlib that the discrete Cayley transform R(theta) = (I - J*theta/2)^(-1) (I + J*theta/2) is unconditionally isometric and strictly preserves the symplectic 2-form omega = dS1 ^ dS2?
Write a syntactically valid Lean 4 theorem and proof script.

MANDATORY NUMERICAL EVALUATION (Section 3):
Compute the exact energy drift observed in our 10,000-step benchmark (initial 3.567271, final 3.350956): [calc: 3.567271 - 3.350956].
Compute the percentage drift rate: [calc: (3.567271 - 3.350956) / 3.567271 * 100.0] %.
Provide the complete Lean 4 theorem.
"""
    },
    {
        "domain": "Information-Theoretic Capacity Bounds on 3-Tier Cognitive Hierarchy",
        "primary_repo": "PRIME-Moment-Attention",
        "secondary_repo": "prime-revisited",
        "web_search": "associative memory capacity bound Hopfield network linear attention channel capacity",
        "target_formulas": ["256 * 64 * 4 / 1024", "73816 / 1024"],
        "problem_prompt": """
Our Wave 4 3-Tier engine unifies a 256-token working memory ring buffer (64 KB) with a 64 KB Titans GTRM episodic manifold.
Derive the formal Shannon-Hopfield associative capacity limit C(W, M) in bits as a function of head dimension D=64, window size W=256, and map size d_map=32.
Prove that the error probability for needle retrieval decays exponentially with signal-to-noise ratio SNR = ||v_needle||^2 / sigma_noise^2.

MANDATORY NUMERICAL EVALUATION (Section 3):
Calculate Tier 1 buffer memory in KB: [calc: 256 * 64 * 4 / 1024] KB.
Calculate total combined 3-tier memory in KB: [calc: 73816 / 1024] KB.
Provide the full mathematical derivation and verification script.
"""
    }
]

# ---------------------------------------------------------------------------
# Main Autonomous Loop v2.0
# ---------------------------------------------------------------------------
def run_autonomous_research_loop():
    track_idx = telemetry.theories_count
    cycle = telemetry.theories_count + 1
    
    print("\n" + "=" * 80)
    print("      FALCON3-10B-1.58BIT AUTONOMOUS RESEARCH DAEMON v2.0 (UPGRADED)")
    print("=" * 80 + "\n")
    
    while True:
        try:
            track = CORE_RESEARCH_TRACKS[track_idx % len(CORE_RESEARCH_TRACKS)]
            domain = track["domain"]
            primary_repo_name = track["primary_repo"]
            secondary_repo_name = track["secondary_repo"]
            web_query = track["web_search"]
            problem_prompt = track["problem_prompt"].strip()
            
            topic_title = f"{domain}: Cycle {cycle}"
            telemetry.update("STUDYING_REPOS", domain, topic_title, cycle)
            print(f"\n[{time.strftime('%X')}] === STARTING RESEARCH CYCLE {cycle} ===")
            print(f"[*] Target Domain: {domain}")
            print(f"[*] Target Repos: {primary_repo_name} & {secondary_repo_name}")
            
            primary_repo = next((r for r in PHIL_REPOS if r["name"] == primary_repo_name), None)
            secondary_repo = next((r for r in PHIL_REPOS if r["name"] == secondary_repo_name), None)
            
            repo_context = ""
            if primary_repo:
                repo_context += sample_repo_context(primary_repo) + "\n\n"
            if secondary_repo:
                repo_context += sample_repo_context(secondary_repo)
            telemetry.repos_studied += 2
            
            telemetry.update("SEARCHING_WEB", domain, topic_title, cycle)
            print(f"[*] Querying Internet for: '{web_query}'...")
            gh_results = search_github(web_query, max_results=2)
            crossref_results = search_crossref(web_query, max_results=2)
            all_literature = gh_results + crossref_results
            telemetry.papers_ingested += len(all_literature)
            
            lit_summary = ""
            for item in all_literature:
                lit_summary += f"- [{item['type'].upper()}] {item['title']} ({item.get('url', '')}): {item['snippet']}\n"
                try:
                    conn = sqlite3.connect(DB_FILE)
                    cur = conn.cursor()
                    cur.execute("""
                    INSERT INTO literature (cycle, timestamp, source_type, title, url, snippet)
                    VALUES (?, ?, ?, ?, ?, ?)
                    """, (cycle, time.strftime("%Y-%m-%d %H:%M:%S"), item["type"], item["title"], item.get("url", ""), item["snippet"]))
                    conn.commit()
                    conn.close()
                except Exception:
                    pass
                    
            print(f"[+] Retrieved {len(all_literature)} relevant external resources.")
            
            # Step 3: Upgraded Deep Formulation
            telemetry.update("THINKING", domain, topic_title, cycle)
            print(f"[*] Prompting Falcon3-10B-1.58bit with anti-leakage constraints & mandatory quantitative tags...")
            
            system_prompt = (
                "You are an elite theoretical physicist, sequence model architect, and applied mathematician. "
                "You are writing formal research papers in Phil's laboratory.\n\n"
                "CRITICAL FORMAT RULES (STRICT):\n"
                "1. NEVER emit JSON commands, tool calls, or schemas (e.g. NEVER write '{\"command\": ...}', 'write_to_file', or 'browse_website'). Write directly in standard technical Markdown.\n"
                "2. Reason through the problem inside <think>...</think>.\n"
                "3. Structure each paper into these 4 sections:\n"
                "   # Theoretical Formulation & Core Thesis\n"
                "   ## Mathematical Derivations & State Transitions\n"
                "   ## Quantitative Numerical Benchmarks: Compute every requested value inside [calc: <formula>] or <<formula>> tags so PRIME-Net can symbolically verify it (e.g. [calc: 32 * 512 * 4]).\n"
                "   ## Implementation & Verification Blueprint (Python / C99)\n"
                "4. Provide non-circular, mathematically rigorous theorems with precise bounds.\n"
                "5. Provide a complete, runnable Python or C99 verification implementation in markdown codeblocks."
            )
            
            user_prompt = f"""
=== FRONTIER RESEARCH CHALLENGE ===
Domain: {domain}
Primary Repository: {primary_repo_name}
Secondary Repository: {secondary_repo_name}

{problem_prompt}

=== EXTERNAL LITERATURE & CODE DISCOVERED ===
{lit_summary}

=== LOCAL REPOSITORY CONTEXT ===
{repo_context}
"""
            messages = [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ]
            
            if hasattr(tokenizer, "apply_chat_template") and tokenizer.chat_template:
                prompt_text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
            else:
                prompt_text = f"System: {system_prompt}\nUser: {user_prompt}\nAssistant: <think>\n"
                
            inputs = tokenizer(prompt_text, return_tensors="pt").to(DEVICE)
            
            def stream_callback(accumulated_text: str, is_end: bool):
                telemetry.update("THINKING", domain, topic_title, cycle, live_thought=accumulated_text)
                
            streamer = LiveThoughtStreamer(tokenizer, on_token_cb=stream_callback)
            
            print(f"[*] Generating theoretical formulation (max 950 new tokens)...")
            gen_start = time.time()
            with torch.no_grad():
                out = model.generate(
                    **inputs,
                    max_new_tokens=950,
                    temperature=0.35,
                    top_p=0.90,
                    do_sample=True,
                    streamer=streamer
                )
            raw_response = tokenizer.decode(out[0][inputs.input_ids.shape[1]:], skip_special_tokens=True).strip()
            
            # Sanitize output (removes any accidental JSON schema leakage)
            clean_response = sanitize_output(raw_response)
            
            # Step 4: PRIME-Net Symbolic Verification
            telemetry.update("VERIFYING", domain, topic_title, cycle, live_thought=clean_response)
            verified_response, injections = cothinker.intercept_and_solve(clean_response, target_formulas=track.get("target_formulas"))
            
            telemetry.formulas_verified += len(injections)
            if injections:
                telemetry.last_formula = f"{injections[0]['expr']} = {injections[0]['result']}"
                print(f"[+] PRIME-Net verified {len(injections)} formulas symbolically in microseconds!")
                for inj in injections:
                    print(f"    - {inj['expr']} = {inj['result']}")
            else:
                print(f"[-] Note: 0 formulas caught by <<...>> pattern.")
                
            # Extract summary & thought
            thought_match = re.search(r"<think>(.*?)</think>", clean_response, re.DOTALL)
            thought_trace = thought_match.group(1).strip() if thought_match else clean_response[:400]
            summary_text = re.sub(r"<think>.*?</think>", "", verified_response, flags=re.DOTALL).strip()
            if not summary_text:
                summary_text = verified_response[:600]
                
            # Step 5: Save Theory to Knowledge Vault
            telemetry.theories_count += 1
            telemetry.last_theory_title = f"Cycle {cycle}: {domain}"
            telemetry.update("SAVING", domain, topic_title, cycle, live_thought=clean_response)
            
            # Record in SQLite
            try:
                conn = sqlite3.connect(DB_FILE)
                cur = conn.cursor()
                cur.execute("""
                INSERT INTO theories (cycle, timestamp, domain, topic, summary, thought_trace, verified_equations, code_solution, external_sources)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
                """, (
                    cycle,
                    time.strftime("%Y-%m-%d %H:%M:%S"),
                    domain,
                    topic_title,
                    summary_text[:1500],
                    thought_trace[:4000],
                    json.dumps(injections),
                    summary_text,
                    json.dumps([item["title"] for item in all_literature])
                ))
                conn.commit()
                conn.close()
            except Exception as e:
                print(f"[-] SQLite insertion error: {e}")
                
            # Record in Markdown Dossier
            with open(DOSSIER_FILE, "a", encoding="utf-8") as f:
                f.write(f"## Cycle {cycle}: {domain}\n\n")
                f.write(f"**Timestamp**: {time.strftime('%Y-%m-%d %H:%M:%S')}  \n")
                f.write(f"**Synthesized Repos**: `{primary_repo_name}` & `{secondary_repo_name}`  \n")
                f.write(f"**External Literature Found**: {len(all_literature)} sources  \n")
                if injections:
                    f.write(f"**PRIME-Net Verifications**: {len(injections)} formulas verified symbolically  \n")
                    for inj in injections:
                        f.write(f"  - `{inj['expr']}` = **`{inj['result']}`**\n")
                f.write("\n### Deep Cognitive Thought Trace\n")
                f.write(f"```text\n{thought_trace[:2500]}\n```\n\n")
                f.write("### Formulated Theory & Solution Blueprint\n\n")
                f.write(f"{summary_text}\n\n")
                f.write("---\n\n")
                
            print(f"[+] Cycle {cycle} complete! Theory saved to {DOSSIER_FILE}")
            
            # Step 6: Advance & Cleanup
            cycle += 1
            track_idx += 1
            
            if torch.cuda.is_available():
                torch.cuda.empty_cache()
                
            time.sleep(5)
            
        except Exception as e:
            print(f"[!] Exception in research cycle: {e}")
            traceback.print_exc()
            time.sleep(10)
            track_idx += 1

if __name__ == "__main__":
    run_autonomous_research_loop()
